// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEyoastPrimaryTerm = "QeyKryWEyoast_primary_term"

// QeyKryWEyoastPrimaryTerm mapped from table <QeyKryWEyoast_primary_term>
type QeyKryWEyoastPrimaryTerm struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PostID    int64     `gorm:"column:post_id" json:"post_id"`
	TermID    int64     `gorm:"column:term_id" json:"term_id"`
	Taxonomy  string    `gorm:"column:taxonomy;not null" json:"taxonomy"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	BlogID    int64     `gorm:"column:blog_id;not null;default:1" json:"blog_id"`
}

// TableName QeyKryWEyoastPrimaryTerm's table name
func (*QeyKryWEyoastPrimaryTerm) TableName() string {
	return TableNameQeyKryWEyoastPrimaryTerm
}
