// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEterm = "QeyKryWEterms"

// QeyKryWEterm mapped from table <QeyKryWEterms>
type QeyKryWEterm struct {
	TermID    int64  `gorm:"column:term_id;primaryKey;autoIncrement:true" json:"term_id"`
	Name      string `gorm:"column:name;not null" json:"name"`
	Slug      string `gorm:"column:slug;not null" json:"slug"`
	TermGroup int64  `gorm:"column:term_group;not null" json:"term_group"`
}

// TableName QeyKryWEterm's table name
func (*QeyKryWEterm) TableName() string {
	return TableNameQeyKryWEterm
}
