// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwflogin = "QeyKryWEwflogins"

// QeyKryWEwflogin mapped from table <QeyKryWEwflogins>
type QeyKryWEwflogin struct {
	ID       int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	HitID    int32   `gorm:"column:hitID" json:"hitID"`
	Ctime    float64 `gorm:"column:ctime;not null" json:"ctime"`
	Fail     int32   `gorm:"column:fail;not null" json:"fail"`
	Action   string  `gorm:"column:action;not null" json:"action"`
	Username string  `gorm:"column:username;not null" json:"username"`
	UserID   int32   `gorm:"column:userID;not null" json:"userID"`
	IP       []byte  `gorm:"column:IP" json:"IP"`
	UA       string  `gorm:"column:UA" json:"UA"`
}

// TableName QeyKryWEwflogin's table name
func (*QeyKryWEwflogin) TableName() string {
	return TableNameQeyKryWEwflogin
}
