// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEyoastSeoLink = "QeyKryWEyoast_seo_links"

// QeyKryWEyoastSeoLink mapped from table <QeyKryWEyoast_seo_links>
type QeyKryWEyoastSeoLink struct {
	ID                int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	URL               string `gorm:"column:url" json:"url"`
	PostID            int64  `gorm:"column:post_id" json:"post_id"`
	TargetPostID      int64  `gorm:"column:target_post_id" json:"target_post_id"`
	Type              string `gorm:"column:type" json:"type"`
	IndexableID       int32  `gorm:"column:indexable_id" json:"indexable_id"`
	TargetIndexableID int32  `gorm:"column:target_indexable_id" json:"target_indexable_id"`
	Height            int32  `gorm:"column:height" json:"height"`
	Width             int32  `gorm:"column:width" json:"width"`
	Size              int32  `gorm:"column:size" json:"size"`
	Language          string `gorm:"column:language" json:"language"`
	Region            string `gorm:"column:region" json:"region"`
}

// TableName QeyKryWEyoastSeoLink's table name
func (*QeyKryWEyoastSeoLink) TableName() string {
	return TableNameQeyKryWEyoastSeoLink
}
