// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEwfwaffailure = "QeyKryWEwfwaffailures"

// QeyKryWEwfwaffailure mapped from table <QeyKryWEwfwaffailures>
type QeyKryWEwfwaffailure struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Throwable string    `gorm:"column:throwable;not null" json:"throwable"`
	RuleID    int32     `gorm:"column:rule_id" json:"rule_id"`
	Timestamp time.Time `gorm:"column:timestamp;not null;default:CURRENT_TIMESTAMP" json:"timestamp"`
}

// TableName QeyKryWEwfwaffailure's table name
func (*QeyKryWEwfwaffailure) TableName() string {
	return TableNameQeyKryWEwfwaffailure
}
