// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEactionschedulerClaim = "QeyKryWEactionscheduler_claims"

// QeyKryWEactionschedulerClaim mapped from table <QeyKryWEactionscheduler_claims>
type QeyKryWEactionschedulerClaim struct {
	ClaimID        int64     `gorm:"column:claim_id;primaryKey;autoIncrement:true" json:"claim_id"`
	DateCreatedGmt time.Time `gorm:"column:date_created_gmt" json:"date_created_gmt"`
}

// TableName QeyKryWEactionschedulerClaim's table name
func (*QeyKryWEactionschedulerClaim) TableName() string {
	return TableNameQeyKryWEactionschedulerClaim
}
