// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwfhit = "QeyKryWEwfhits"

// QeyKryWEwfhit mapped from table <QeyKryWEwfhits>
type QeyKryWEwfhit struct {
	ID                int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AttackLogTime     float64 `gorm:"column:attackLogTime;not null" json:"attackLogTime"`
	Ctime             float64 `gorm:"column:ctime;not null" json:"ctime"`
	IP                []byte  `gorm:"column:IP" json:"IP"`
	JsRun             int32   `gorm:"column:jsRun" json:"jsRun"`
	StatusCode        int32   `gorm:"column:statusCode;not null;default:200" json:"statusCode"`
	IsGoogle          int32   `gorm:"column:isGoogle;not null" json:"isGoogle"`
	UserID            int32   `gorm:"column:userID;not null" json:"userID"`
	NewVisit          int32   `gorm:"column:newVisit;not null" json:"newVisit"`
	URL               string  `gorm:"column:URL" json:"URL"`
	Referer           string  `gorm:"column:referer" json:"referer"`
	UA                string  `gorm:"column:UA" json:"UA"`
	Action            string  `gorm:"column:action;not null" json:"action"`
	ActionDescription string  `gorm:"column:actionDescription" json:"actionDescription"`
	ActionData        string  `gorm:"column:actionData" json:"actionData"`
}

// TableName QeyKryWEwfhit's table name
func (*QeyKryWEwfhit) TableName() string {
	return TableNameQeyKryWEwfhit
}
