// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEactionschedulerLog = "QeyKryWEactionscheduler_logs"

// QeyKryWEactionschedulerLog mapped from table <QeyKryWEactionscheduler_logs>
type QeyKryWEactionschedulerLog struct {
	LogID        int64     `gorm:"column:log_id;primaryKey;autoIncrement:true" json:"log_id"`
	ActionID     int64     `gorm:"column:action_id;not null" json:"action_id"`
	Message      string    `gorm:"column:message;not null" json:"message"`
	LogDateGmt   time.Time `gorm:"column:log_date_gmt" json:"log_date_gmt"`
	LogDateLocal time.Time `gorm:"column:log_date_local" json:"log_date_local"`
}

// TableName QeyKryWEactionschedulerLog's table name
func (*QeyKryWEactionschedulerLog) TableName() string {
	return TableNameQeyKryWEactionschedulerLog
}
