// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEmrRatingItemEntry = "QeyKryWEmr_rating_item_entry"

// QeyKryWEmrRatingItemEntry mapped from table <QeyKryWEmr_rating_item_entry>
type QeyKryWEmrRatingItemEntry struct {
	RatingItemEntryID int64     `gorm:"column:rating_item_entry_id;primaryKey;autoIncrement:true" json:"rating_item_entry_id"`
	PostID            int64     `gorm:"column:post_id;not null" json:"post_id"`
	EntryDate         time.Time `gorm:"column:entry_date;not null" json:"entry_date"`
	UserID            int64     `gorm:"column:user_id" json:"user_id"`
}

// TableName QeyKryWEmrRatingItemEntry's table name
func (*QeyKryWEmrRatingItemEntry) TableName() string {
	return TableNameQeyKryWEmrRatingItemEntry
}
