// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwfblockediplog = "QeyKryWEwfblockediplog"

// QeyKryWEwfblockediplog mapped from table <QeyKryWEwfblockediplog>
type QeyKryWEwfblockediplog struct {
	IP          []byte `gorm:"column:IP;primaryKey;default:0x" json:"IP"`
	CountryCode string `gorm:"column:countryCode;not null" json:"countryCode"`
	BlockCount  int32  `gorm:"column:blockCount;not null" json:"blockCount"`
	Unixday     int32  `gorm:"column:unixday;primaryKey" json:"unixday"`
	BlockType   string `gorm:"column:blockType;primaryKey;default:generic" json:"blockType"`
}

// TableName QeyKryWEwfblockediplog's table name
func (*QeyKryWEwfblockediplog) TableName() string {
	return TableNameQeyKryWEwfblockediplog
}
