// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEulikeComment = "QeyKryWEulike_comments"

// QeyKryWEulikeComment mapped from table <QeyKryWEulike_comments>
type QeyKryWEulikeComment struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommentID int64     `gorm:"column:comment_id;not null" json:"comment_id"`
	DateTime  time.Time `gorm:"column:date_time;not null" json:"date_time"`
	IP        string    `gorm:"column:ip;not null" json:"ip"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Status    string    `gorm:"column:status;not null" json:"status"`
}

// TableName QeyKryWEulikeComment's table name
func (*QeyKryWEulikeComment) TableName() string {
	return TableNameQeyKryWEulikeComment
}
