// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEsnippet = "QeyKryWEsnippets"

// QeyKryWEsnippet mapped from table <QeyKryWEsnippets>
type QeyKryWEsnippet struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Code        string    `gorm:"column:code;not null" json:"code"`
	Tags        string    `gorm:"column:tags;not null" json:"tags"`
	Scope       string    `gorm:"column:scope;not null;default:global" json:"scope"`
	Priority    int32     `gorm:"column:priority;not null;default:10" json:"priority"`
	Active      bool      `gorm:"column:active;not null" json:"active"`
	Modified    time.Time `gorm:"column:modified;not null" json:"modified"`
}

// TableName QeyKryWEsnippet's table name
func (*QeyKryWEsnippet) TableName() string {
	return TableNameQeyKryWEsnippet
}
