// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEnggGallery = "QeyKryWEngg_gallery"

// QeyKryWEnggGallery mapped from table <QeyKryWEngg_gallery>
type QeyKryWEnggGallery struct {
	Gid          int64  `gorm:"column:gid;primaryKey;autoIncrement:true" json:"gid"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Slug         string `gorm:"column:slug;not null" json:"slug"`
	Path         string `gorm:"column:path" json:"path"`
	Title        string `gorm:"column:title" json:"title"`
	Galdesc      string `gorm:"column:galdesc" json:"galdesc"`
	Pageid       int64  `gorm:"column:pageid;not null" json:"pageid"`
	Previewpic   int64  `gorm:"column:previewpic;not null" json:"previewpic"`
	Author       int64  `gorm:"column:author;not null" json:"author"`
	ExtrasPostID int64  `gorm:"column:extras_post_id;not null" json:"extras_post_id"`
}

// TableName QeyKryWEnggGallery's table name
func (*QeyKryWEnggGallery) TableName() string {
	return TableNameQeyKryWEnggGallery
}
