// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwcUsersRated = "QeyKryWEwc_users_rated"

// QeyKryWEwcUsersRated mapped from table <QeyKryWEwc_users_rated>
type QeyKryWEwcUsersRated struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PostID int32  `gorm:"column:post_id;not null" json:"post_id"`
	UserID int32  `gorm:"column:user_id;not null" json:"user_id"`
	UserIP string `gorm:"column:user_ip;not null" json:"user_ip"`
	Rating int32  `gorm:"column:rating;not null" json:"rating"`
	Date   int32  `gorm:"column:date;not null" json:"date"`
}

// TableName QeyKryWEwcUsersRated's table name
func (*QeyKryWEwcUsersRated) TableName() string {
	return TableNameQeyKryWEwcUsersRated
}
