// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEcomment = "QeyKryWEcomments"

// QeyKryWEcomment mapped from table <QeyKryWEcomments>
type QeyKryWEcomment struct {
	CommentID          int64     `gorm:"column:comment_ID;primaryKey;autoIncrement:true" json:"comment_ID"`
	CommentPostID      int64     `gorm:"column:comment_post_ID;not null" json:"comment_post_ID"`
	CommentAuthor      string    `gorm:"column:comment_author;not null" json:"comment_author"`
	CommentAuthorEmail string    `gorm:"column:comment_author_email;not null" json:"comment_author_email"`
	CommentAuthorURL   string    `gorm:"column:comment_author_url;not null" json:"comment_author_url"`
	CommentAuthorIP    string    `gorm:"column:comment_author_IP;not null" json:"comment_author_IP"`
	CommentDate        time.Time `gorm:"column:comment_date;not null" json:"comment_date"`
	CommentDateGmt     time.Time `gorm:"column:comment_date_gmt;not null" json:"comment_date_gmt"`
	CommentContent     string    `gorm:"column:comment_content;not null" json:"comment_content"`
	CommentKarma       int32     `gorm:"column:comment_karma;not null" json:"comment_karma"`
	CommentApproved    string    `gorm:"column:comment_approved;not null;default:1" json:"comment_approved"`
	CommentAgent       string    `gorm:"column:comment_agent;not null" json:"comment_agent"`
	CommentType        string    `gorm:"column:comment_type;not null;default:comment" json:"comment_type"`
	CommentParent      int64     `gorm:"column:comment_parent;not null" json:"comment_parent"`
	UserID             int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName QeyKryWEcomment's table name
func (*QeyKryWEcomment) TableName() string {
	return TableNameQeyKryWEcomment
}
