// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwfstatus = "QeyKryWEwfstatus"

// QeyKryWEwfstatus mapped from table <QeyKryWEwfstatus>
type QeyKryWEwfstatus struct {
	ID    int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Ctime float64 `gorm:"column:ctime;not null" json:"ctime"`
	Level int32   `gorm:"column:level;not null" json:"level"`
	Type  string  `gorm:"column:type;not null" json:"type"`
	Msg   string  `gorm:"column:msg;not null" json:"msg"`
}

// TableName QeyKryWEwfstatus's table name
func (*QeyKryWEwfstatus) TableName() string {
	return TableNameQeyKryWEwfstatus
}
