// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwcPhrase = "QeyKryWEwc_phrases"

// QeyKryWEwcPhrase mapped from table <QeyKryWEwc_phrases>
type QeyKryWEwcPhrase struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PhraseKey   string `gorm:"column:phrase_key;not null" json:"phrase_key"`
	PhraseValue string `gorm:"column:phrase_value;not null" json:"phrase_value"`
}

// TableName QeyKryWEwcPhrase's table name
func (*QeyKryWEwcPhrase) TableName() string {
	return TableNameQeyKryWEwcPhrase
}
