// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwfhoover = "QeyKryWEwfhoover"

// QeyKryWEwfhoover mapped from table <QeyKryWEwfhoover>
type QeyKryWEwfhoover struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Owner   string `gorm:"column:owner" json:"owner"`
	Host    string `gorm:"column:host" json:"host"`
	Path    string `gorm:"column:path" json:"path"`
	HostKey []byte `gorm:"column:hostKey" json:"hostKey"`
}

// TableName QeyKryWEwfhoover's table name
func (*QeyKryWEwfhoover) TableName() string {
	return TableNameQeyKryWEwfhoover
}
