// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEwpmailsmtpDebugEvent = "QeyKryWEwpmailsmtp_debug_events"

// QeyKryWEwpmailsmtpDebugEvent mapped from table <QeyKryWEwpmailsmtp_debug_events>
type QeyKryWEwpmailsmtpDebugEvent struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content   string    `gorm:"column:content" json:"content"`
	Initiator string    `gorm:"column:initiator" json:"initiator"`
	EventType int32     `gorm:"column:event_type;not null" json:"event_type"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName QeyKryWEwpmailsmtpDebugEvent's table name
func (*QeyKryWEwpmailsmtpDebugEvent) TableName() string {
	return TableNameQeyKryWEwpmailsmtpDebugEvent
}
