// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEjetpackWafBlocklog = "QeyKryWEjetpack_waf_blocklog"

// QeyKryWEjetpackWafBlocklog mapped from table <QeyKryWEjetpack_waf_blocklog>
type QeyKryWEjetpackWafBlocklog struct {
	LogID     int64     `gorm:"column:log_id;primaryKey;autoIncrement:true" json:"log_id"`
	Timestamp time.Time `gorm:"column:timestamp;not null" json:"timestamp"`
	RuleID    int64     `gorm:"column:rule_id;not null" json:"rule_id"`
	Reason    string    `gorm:"column:reason;not null" json:"reason"`
}

// TableName QeyKryWEjetpackWafBlocklog's table name
func (*QeyKryWEjetpackWafBlocklog) TableName() string {
	return TableNameQeyKryWEjetpackWafBlocklog
}
