// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwffilechange = "QeyKryWEwffilechanges"

// QeyKryWEwffilechange mapped from table <QeyKryWEwffilechanges>
type QeyKryWEwffilechange struct {
	FilenameHash string `gorm:"column:filenameHash;primaryKey" json:"filenameHash"`
	File         string `gorm:"column:file;not null" json:"file"`
	Md5          string `gorm:"column:md5;not null" json:"md5"`
}

// TableName QeyKryWEwffilechange's table name
func (*QeyKryWEwffilechange) TableName() string {
	return TableNameQeyKryWEwffilechange
}
