// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEusermetum = "QeyKryWEusermeta"

// QeyKryWEusermetum mapped from table <QeyKryWEusermeta>
type QeyKryWEusermetum struct {
	UmetaID   int64  `gorm:"column:umeta_id;primaryKey;autoIncrement:true" json:"umeta_id"`
	UserID    int64  `gorm:"column:user_id;not null" json:"user_id"`
	MetaKey   string `gorm:"column:meta_key" json:"meta_key"`
	MetaValue string `gorm:"column:meta_value" json:"meta_value"`
}

// TableName QeyKryWEusermetum's table name
func (*QeyKryWEusermetum) TableName() string {
	return TableNameQeyKryWEusermetum
}
