// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWElikeDislikeBtnDetail = "QeyKryWElike_dislike_btn_details"

// QeyKryWElikeDislikeBtnDetail mapped from table <QeyKryWElike_dislike_btn_details>
type QeyKryWElikeDislikeBtnDetail struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BtnContainer    string `gorm:"column:btn_container" json:"btn_container"`
	LikeDislikeType string `gorm:"column:likeDislikeType" json:"likeDislikeType"`
	ShowOneHome     string `gorm:"column:show_one_home" json:"show_one_home"`
	OnPages         string `gorm:"column:on_pages" json:"on_pages"`
	OnProductPage   string `gorm:"column:on_product_page" json:"on_product_page"`
	OnshowShare     string `gorm:"column:onshowShare" json:"onshowShare"`
}

// TableName QeyKryWElikeDislikeBtnDetail's table name
func (*QeyKryWElikeDislikeBtnDetail) TableName() string {
	return TableNameQeyKryWElikeDislikeBtnDetail
}
