// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameQeyKryWEulikeActivity = "QeyKryWEulike_activities"

// QeyKryWEulikeActivity mapped from table <QeyKryWEulike_activities>
type QeyKryWEulikeActivity struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ActivityID int64     `gorm:"column:activity_id;not null" json:"activity_id"`
	DateTime   time.Time `gorm:"column:date_time;not null" json:"date_time"`
	IP         string    `gorm:"column:ip;not null" json:"ip"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	Status     string    `gorm:"column:status;not null" json:"status"`
}

// TableName QeyKryWEulikeActivity's table name
func (*QeyKryWEulikeActivity) TableName() string {
	return TableNameQeyKryWEulikeActivity
}
