// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwfloc = "QeyKryWEwflocs"

// QeyKryWEwfloc mapped from table <QeyKryWEwflocs>
type QeyKryWEwfloc struct {
	IP          []byte  `gorm:"column:IP;primaryKey;default:0x" json:"IP"`
	Ctime       int32   `gorm:"column:ctime;not null" json:"ctime"`
	Failed      int32   `gorm:"column:failed;not null" json:"failed"`
	City        string  `gorm:"column:city" json:"city"`
	Region      string  `gorm:"column:region" json:"region"`
	CountryName string  `gorm:"column:countryName" json:"countryName"`
	CountryCode string  `gorm:"column:countryCode" json:"countryCode"`
	Lat         float32 `gorm:"column:lat;default:0.0000000" json:"lat"`
	Lon         float32 `gorm:"column:lon;default:0.0000000" json:"lon"`
}

// TableName QeyKryWEwfloc's table name
func (*QeyKryWEwfloc) TableName() string {
	return TableNameQeyKryWEwfloc
}
