// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQeyKryWEwfconfig = "QeyKryWEwfconfig"

// QeyKryWEwfconfig mapped from table <QeyKryWEwfconfig>
type QeyKryWEwfconfig struct {
	Name     string `gorm:"column:name;primaryKey" json:"name"`
	Val      []byte `gorm:"column:val" json:"val"`
	Autoload string `gorm:"column:autoload;not null;default:yes" json:"autoload"`
}

// TableName QeyKryWEwfconfig's table name
func (*QeyKryWEwfconfig) TableName() string {
	return TableNameQeyKryWEwfconfig
}
