version: '3.7'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3999:3306"
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: webapp
      MYSQL_DATABASE: webapp
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/app/pb_data
      - ./web:/app/web
    restart: unless-stopped