version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/app/pb_data
      - ./web:/app/web
    restart: unless-stopped