version: '3.7'

services:
  db:
    image: mariadb:lts
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3999:3306"
    volumes:
      - ./dbdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: webapp
      MYSQL_DATABASE: webapp
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 3s
      interval: 3s
      timeout: 5s
      retries: 30
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - type: bind
        source: ./pb_data
        target: /app/pb_data
      - type: bind
        source: ./web
        target: /app/web
      - type: bind
        source: ./server
        target: /app/server
      - type: bind
        source: ./internal
        target: /app/internal
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy