package schematic

import (
	"archive/zip"
	"bytes"
	"compress/zlib"
	"fmt"
	"io"
	"math/bits"

	"github.com/Tnze/go-mc/level"
	"github.com/Tnze/go-mc/nbt"
	"github.com/Tnze/go-mc/save/region"
)

// World export: the model placed into a ready-to-play superflat save. The
// output zip contains <name>/level.dat plus region/*.mca covering the build;
// chunks outside the build are generated by the game's flat generator, so
// our chunks include the same flat layers to blend seamlessly.
//
// Layout (fixed, deterministic):
//   - classic flat preset: bedrock at y=-64, dirt -63..-62, grass at -61
//   - build min corner at (0, -60, 0), standing on the grass
//   - spawn a few blocks south of the build, facing it (creative,
//     daylight cycle and mob spawning off, keepInventory on)

// World export guards: generation runs in the request path.
const (
	MaxWorldExportDim    = 1008 // horizontal blocks (63 chunks)
	MaxWorldExportHeight = 316  // fits -60..255 with headroom
)

const (
	worldBaseY    = -60 // build min corner sits on the grass surface
	worldMinY     = -64
	sectionMinY   = -4 // y=-64
	grassY        = -61
	flatSurfaceDV = 3465 // fallback DataVersion (1.20.1) for old/unknown builds
)

// dataVersionNames maps known DataVersions to display names for level.dat.
var dataVersionNames = map[int]string{
	2975: "1.18.2", 3120: "1.19.2", 3218: "1.19.3", 3337: "1.19.4",
	3465: "1.20.1", 3578: "1.20.2", 3700: "1.20.4", 3839: "1.20.6",
	3955: "1.21.1", 4082: "1.21.3", 4189: "1.21.4",
}

// CanExportWorld reports whether a build fits the world-export guards.
func CanExportWorld(dims [3]int) (bool, string) {
	if dims[0] <= 0 || dims[1] <= 0 || dims[2] <= 0 {
		return false, "unknown size"
	}
	if dims[0] > MaxWorldExportDim || dims[2] > MaxWorldExportDim {
		return false, fmt.Sprintf("footprint exceeds %d blocks", MaxWorldExportDim)
	}
	if dims[1] > MaxWorldExportHeight {
		return false, fmt.Sprintf("taller than %d blocks", MaxWorldExportHeight)
	}
	if v := dims[0] * dims[1] * dims[2]; v > MaxWorldExportVolume {
		return false, "volume too large for world export"
	}
	return true, ""
}

// worldDataVersion picks the chunk/level DataVersion for a build.
func worldDataVersion(dv int) (int, bool) {
	if dv >= 2975 {
		return dv, false
	}
	return flatSurfaceDV, true // pre-1.18.2 or unknown: clamp with warning
}

type worldBlockStates struct {
	Palette []structPaletteEntryOut `nbt:"palette"`
	Data    []int64                 `nbt:"data,omitempty"`
}

type worldBiomes struct {
	Palette []string `nbt:"palette"`
}

type worldSection struct {
	Y           int8             `nbt:"Y"`
	BlockStates worldBlockStates `nbt:"block_states"`
	Biomes      worldBiomes      `nbt:"biomes"`
}

type worldChunk struct {
	DataVersion   int32          `nbt:"DataVersion"`
	XPos          int32          `nbt:"xPos"`
	YPos          int32          `nbt:"yPos"`
	ZPos          int32          `nbt:"zPos"`
	Status        string         `nbt:"Status"`
	LastUpdate    int64          `nbt:"LastUpdate"`
	InhabitedTime int64          `nbt:"InhabitedTime"`
	Sections      []worldSection `nbt:"sections"`
	BlockEntities rawList        `nbt:"block_entities"`
}

// memFile is an in-memory io.ReadWriteSeeker for region.CreateWriter.
type memFile struct {
	buf []byte
	pos int64
}

func (m *memFile) Read(p []byte) (int, error) {
	if m.pos >= int64(len(m.buf)) {
		return 0, io.EOF
	}
	n := copy(p, m.buf[m.pos:])
	m.pos += int64(n)
	return n, nil
}

func (m *memFile) Write(p []byte) (int, error) {
	end := m.pos + int64(len(p))
	if end > int64(len(m.buf)) {
		grown := make([]byte, end)
		copy(grown, m.buf)
		m.buf = grown
	}
	copy(m.buf[m.pos:end], p)
	m.pos = end
	return len(p), nil
}

func (m *memFile) Seek(offset int64, whence int) (int64, error) {
	switch whence {
	case io.SeekStart:
		m.pos = offset
	case io.SeekCurrent:
		m.pos += offset
	case io.SeekEnd:
		m.pos = int64(len(m.buf)) + offset
	}
	if m.pos < 0 {
		return 0, fmt.Errorf("negative seek")
	}
	return m.pos, nil
}

// sectionBuilder accumulates one 16³ section's palette + indices.
type sectionBuilder struct {
	palette  []structPaletteEntryOut
	keys     map[string]int
	indices  [4096]int
	nonEmpty bool
}

func newSectionBuilder(baseBlocks []structPaletteEntryOut) *sectionBuilder {
	sb := &sectionBuilder{keys: map[string]int{}}
	for _, e := range baseBlocks {
		sb.paletteIndex(e)
	}
	return sb
}

func (sb *sectionBuilder) paletteIndex(e structPaletteEntryOut) int {
	key := e.Name
	if len(e.Properties) > 0 {
		key = BlockState{Name: e.Name, Properties: e.Properties}.Key()
	}
	if i, ok := sb.keys[key]; ok {
		return i
	}
	sb.palette = append(sb.palette, e)
	sb.keys[key] = len(sb.palette) - 1
	return len(sb.palette) - 1
}

func (sb *sectionBuilder) set(x, y, z int, e structPaletteEntryOut) {
	idx := sb.paletteIndex(e)
	sb.indices[(y*16+z)*16+x] = idx
	if idx != 0 {
		sb.nonEmpty = true
	}
}

func (sb *sectionBuilder) build(y int8) worldSection {
	sec := worldSection{
		Y:      y,
		Biomes: worldBiomes{Palette: []string{"minecraft:plains"}},
	}
	sec.BlockStates.Palette = sb.palette
	if len(sb.palette) > 1 {
		bitsPer := bits.Len(uint(len(sb.palette) - 1))
		if bitsPer < 4 {
			bitsPer = 4
		}
		storage := level.NewBitStorage(bitsPer, 4096, nil)
		for i, v := range sb.indices {
			storage.Set(i, v)
		}
		raw := storage.Raw()
		data := make([]int64, len(raw))
		for i, u := range raw {
			data[i] = int64(u)
		}
		sec.BlockStates.Data = data
	}
	return sec
}

var (
	worldAir     = structPaletteEntryOut{Name: "minecraft:air"}
	worldBedrock = structPaletteEntryOut{Name: "minecraft:bedrock"}
	worldDirt    = structPaletteEntryOut{Name: "minecraft:dirt"}
	worldGrass   = structPaletteEntryOut{Name: "minecraft:grass_block", Properties: propsMap{"snowy": "false"}}
)

// flatBlockAt returns the flat-preset block for a world y (below the build).
func flatBlockAt(wy int) (structPaletteEntryOut, bool) {
	switch {
	case wy == worldMinY:
		return worldBedrock, true
	case wy > worldMinY && wy < grassY:
		return worldDirt, true
	case wy == grassY:
		return worldGrass, true
	default:
		return worldAir, false
	}
}

// WriteWorld streams a ready-to-play world zip for the model.
func WriteWorld(s *Schematic, worldName string, w io.Writer) ([]Warning, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	if ok, reason := CanExportWorld(s.Size); !ok {
		return nil, fmt.Errorf("schematic: %s — download the schematic instead", reason)
	}
	var warnings []Warning
	dv, clamped := worldDataVersion(s.DataVersion)
	if clamped {
		warnings = append(warnings, Warning{Message: fmt.Sprintf(
			"build has an old or unknown Minecraft version; the world targets %s — very old block names may need in-game fixing", dataVersionNames[dv])})
	}
	if len(s.Entities) > 0 {
		warnings = append(warnings, Warning{Message: fmt.Sprintf("%d entities are not placed in the world", len(s.Entities))})
	}

	status := "full"
	if dv >= 3463 {
		status = "minecraft:full"
	}

	// Block entities by chunk, payload re-framed with world coordinates.
	beByChunk := map[[2]int]rawList{}
	for _, be := range s.BlockEntities {
		fields, err := compoundFields(be.Raw)
		if err != nil {
			continue
		}
		wx, wy, wz := be.Pos[0], be.Pos[1]+worldBaseY, be.Pos[2]
		fields["x"] = rawInt(int32(wx))
		fields["y"] = rawInt(int32(wy))
		fields["z"] = rawInt(int32(wz))
		key := [2]int{wx >> 4, wz >> 4}
		beByChunk[key] = append(beByChunk[key], compoundFromFields(fields))
	}

	zw := zip.NewWriter(w)

	// level.dat (gzipped NBT)
	levelFile, err := zw.Create(worldName + "/level.dat")
	if err != nil {
		return nil, err
	}
	levelBytes, err := buildLevelDat(s, worldName, dv)
	if err != nil {
		return nil, err
	}
	if _, err := levelFile.Write(levelBytes); err != nil {
		return nil, err
	}

	// Region files. Build occupies chunks (0,0)..(maxCX,maxCZ).
	maxCX := (s.Size[0] - 1) >> 4
	maxCZ := (s.Size[2] - 1) >> 4
	topY := worldBaseY + s.Size[1] - 1
	maxSection := topY >> 4 // section containing the top block
	if maxSection < sectionMinY {
		maxSection = sectionMinY
	}

	for rz := 0; rz <= maxCZ>>5; rz++ {
		for rx := 0; rx <= maxCX>>5; rx++ {
			mf := &memFile{}
			reg, err := region.CreateWriter(mf)
			if err != nil {
				return nil, err
			}
			for cz := rz << 5; cz <= maxCZ && cz < (rz+1)<<5; cz++ {
				for cx := rx << 5; cx <= maxCX && cx < (rx+1)<<5; cx++ {
					chunkNBT, err := buildChunk(s, cx, cz, dv, status, maxSection, beByChunk[[2]int{cx, cz}])
					if err != nil {
						return nil, err
					}
					var comp bytes.Buffer
					comp.WriteByte(2) // zlib scheme
					zl := zlib.NewWriter(&comp)
					if _, err := zl.Write(chunkNBT); err != nil {
						return nil, err
					}
					if err := zl.Close(); err != nil {
						return nil, err
					}
					lx, lz := region.In(cx, cz)
					if err := reg.WriteSector(lx, lz, comp.Bytes()); err != nil {
						return nil, err
					}
				}
			}
			if err := reg.Close(); err != nil {
				return nil, err
			}
			// Pad to a whole 4096-byte sector: go-mc stops at the last chunk
			// byte, but Minecraft expects sector-aligned region files and
			// logs "truncated" warnings otherwise.
			if rem := len(mf.buf) % 4096; rem != 0 {
				mf.buf = append(mf.buf, make([]byte, 4096-rem)...)
			}
			regFile, err := zw.Create(fmt.Sprintf("%s/region/r.%d.%d.mca", worldName, rx, rz))
			if err != nil {
				return nil, err
			}
			if _, err := regFile.Write(mf.buf); err != nil {
				return nil, err
			}
		}
	}

	return warnings, zw.Close()
}

// buildChunk assembles one chunk's NBT (uncompressed).
func buildChunk(s *Schematic, cx, cz int, dv int, status string, maxSection int, blockEntities rawList) ([]byte, error) {
	chunk := worldChunk{
		DataVersion:   int32(dv),
		XPos:          int32(cx),
		YPos:          int32(sectionMinY),
		ZPos:          int32(cz),
		Status:        status,
		BlockEntities: blockEntities,
	}
	if chunk.BlockEntities == nil {
		chunk.BlockEntities = rawList{}
	}

	for sy := sectionMinY; sy <= maxSection; sy++ {
		sb := newSectionBuilder([]structPaletteEntryOut{worldAir})
		for ly := 0; ly < 16; ly++ {
			wy := sy*16 + ly
			// flat preset layers
			if flat, ok := flatBlockAt(wy); ok {
				for lz := 0; lz < 16; lz++ {
					for lx := 0; lx < 16; lx++ {
						sb.set(lx, ly, lz, flat)
					}
				}
				continue
			}
			by := wy - worldBaseY // build-local y
			if by < 0 || by >= s.Size[1] {
				continue
			}
			for lz := 0; lz < 16; lz++ {
				bz := cz*16 + lz
				if bz >= s.Size[2] {
					break
				}
				for lx := 0; lx < 16; lx++ {
					bx := cx*16 + lx
					if bx >= s.Size[0] {
						break
					}
					st := s.Palette[s.Blocks[s.Index(bx, by, bz)]]
					if st.IsAir() {
						continue
					}
					sb.set(lx, ly, lz, structPaletteEntryOut{Name: st.Name, Properties: st.Properties})
				}
			}
		}
		chunk.Sections = append(chunk.Sections, sb.build(int8(sy)))
	}

	var buf bytes.Buffer
	if err := nbt.NewEncoder(&buf).Encode(chunk, ""); err != nil {
		return nil, fmt.Errorf("schematic: encode chunk %d,%d: %w", cx, cz, err)
	}
	return buf.Bytes(), nil
}

type levelVersion struct {
	ID       int32  `nbt:"Id"`
	Name     string `nbt:"Name"`
	Series   string `nbt:"Series"`
	Snapshot int8   `nbt:"Snapshot"`
}

type flatLayer struct {
	Block  string `nbt:"block"`
	Height int32  `nbt:"height"`
}

type levelDat struct {
	Data struct {
		DataVersion    int32             `nbt:"DataVersion"`
		VersionInt     int32             `nbt:"version"`
		Version        levelVersion      `nbt:"Version"`
		LevelName      string            `nbt:"LevelName"`
		GameType       int32             `nbt:"GameType"`
		Difficulty     int8              `nbt:"Difficulty"`
		AllowCommands  int8              `nbt:"allowCommands"`
		Hardcore       int8              `nbt:"hardcore"`
		Initialized    int8              `nbt:"initialized"`
		SpawnX         int32             `nbt:"SpawnX"`
		SpawnY         int32             `nbt:"SpawnY"`
		SpawnZ         int32             `nbt:"SpawnZ"`
		SpawnAngle     float32           `nbt:"SpawnAngle"`
		Time           int64             `nbt:"Time"`
		DayTime        int64             `nbt:"DayTime"`
		LastPlayed     int64             `nbt:"LastPlayed"`
		GameRules      map[string]string `nbt:"GameRules"`
		WorldGenSettings struct {
			BonusChest       int8  `nbt:"bonus_chest"`
			GenerateFeatures int8  `nbt:"generate_features"`
			Seed             int64 `nbt:"seed"`
			Dimensions       struct {
				Overworld struct {
					Type      string `nbt:"type"`
					Generator struct {
						Type     string `nbt:"type"`
						Settings struct {
							Layers   []flatLayer `nbt:"layers"`
							Biome    string      `nbt:"biome"`
							Features int8        `nbt:"features"`
							Lakes    int8        `nbt:"lakes"`
						} `nbt:"settings"`
					} `nbt:"generator"`
				} `nbt:"minecraft:overworld"`
				Nether struct {
					Type      string `nbt:"type"`
					Generator struct {
						Type        string `nbt:"type"`
						Settings    string `nbt:"settings"`
						BiomeSource struct {
							Type   string `nbt:"type"`
							Preset string `nbt:"preset"`
						} `nbt:"biome_source"`
					} `nbt:"generator"`
				} `nbt:"minecraft:the_nether"`
				End struct {
					Type      string `nbt:"type"`
					Generator struct {
						Type        string `nbt:"type"`
						Settings    string `nbt:"settings"`
						BiomeSource struct {
							Type string `nbt:"type"`
						} `nbt:"biome_source"`
					} `nbt:"generator"`
				} `nbt:"minecraft:the_end"`
			} `nbt:"dimensions"`
		} `nbt:"WorldGenSettings"`
	} `nbt:"Data"`
}

// buildLevelDat renders a gzipped level.dat with deterministic settings.
func buildLevelDat(s *Schematic, worldName string, dv int) ([]byte, error) {
	var ld levelDat
	d := &ld.Data
	d.DataVersion = int32(dv)
	d.VersionInt = 19133
	name := dataVersionNames[dv]
	if name == "" {
		name = fmt.Sprintf("data version %d", dv)
	}
	d.Version = levelVersion{ID: int32(dv), Name: name, Series: "main"}
	d.LevelName = worldName
	d.GameType = 1 // creative
	d.AllowCommands = 1
	d.Initialized = 1
	// Spawn a few blocks south of the build's center-south edge, facing it.
	d.SpawnX = int32(s.Size[0] / 2)
	d.SpawnY = int32(worldBaseY)
	d.SpawnZ = int32(s.Size[2] + 4)
	d.SpawnAngle = 180 // facing -z, toward the build
	d.Time = 6000
	d.DayTime = 6000
	d.GameRules = map[string]string{
		"doDaylightCycle": "false",
		"doWeatherCycle":  "false",
		"doMobSpawning":   "false",
		"keepInventory":   "true",
	}
	wgs := &d.WorldGenSettings
	ow := &wgs.Dimensions.Overworld
	ow.Type = "minecraft:overworld"
	ow.Generator.Type = "minecraft:flat"
	ow.Generator.Settings.Layers = []flatLayer{
		{Block: "minecraft:bedrock", Height: 1},
		{Block: "minecraft:dirt", Height: 2},
		{Block: "minecraft:grass_block", Height: 1},
	}
	ow.Generator.Settings.Biome = "minecraft:plains"
	ne := &wgs.Dimensions.Nether
	ne.Type = "minecraft:the_nether"
	ne.Generator.Type = "minecraft:noise"
	ne.Generator.Settings = "minecraft:nether"
	ne.Generator.BiomeSource.Type = "minecraft:multi_noise"
	ne.Generator.BiomeSource.Preset = "minecraft:nether"
	end := &wgs.Dimensions.End
	end.Type = "minecraft:the_end"
	end.Generator.Type = "minecraft:noise"
	end.Generator.Settings = "minecraft:end"
	end.Generator.BiomeSource.Type = "minecraft:the_end"

	var buf bytes.Buffer
	if err := nbt.NewEncoder(&buf).Encode(ld, ""); err != nil {
		return nil, fmt.Errorf("schematic: encode level.dat: %w", err)
	}
	return gzipBytes(buf.Bytes())
}
