import React from 'react';
import Layout from '../components/layout/Layout';
import Link from 'next/link';
import { getCategories } from '../lib/api';

/**
 * Guide page component
 * 
 * @param {Object} props - Component props from getServerSideProps
 * @param {Array} props.categories - Categories data for sidebar
 */
export default function Guide({ categories = [] }) {
  return (
    <Layout 
      title="Guide - CreateMod.com"
      description="Comprehensive guide for using Create mod and sharing schematics on CreateMod.com"
      categories={categories}
    >
      <div className="container-xl py-4">
        <div className="card">
          <div className="card-header">
            <h2 className="card-title">Create Mod Guide</h2>
          </div>
          <div className="card-body">
            <div className="markdown">
              <h3>Getting Started with Create Mod</h3>
              <p>
                Welcome to our comprehensive guide for the Create mod and CreateMod.com! Whether you're new to the mod or looking to share your creations, this guide will help you get started.
              </p>
              
              <div className="alert alert-info mb-4">
                <div className="d-flex">
                  <div>
                    <svg xmlns="http://www.w3.org/2000/svg" className="icon alert-icon" width="24" height="24" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor" fill="none" strokeLinecap="round" strokeLinejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M12 9h.01"></path>
                      <path d="M11 12h1v4h1"></path>
                      <path d="M12 3c7.2 0 9 1.8 9 9s-1.8 9 -9 9s-9 -1.8 -9 -9s1.8 -9 9 -9z"></path>
                    </svg>
                  </div>
                  <div>
                    <h4 className="alert-title">Note</h4>
                    <p>This guide is for Create mod version 0.5.1 and above. Some features may differ in older versions.</p>
                  </div>
                </div>
              </div>
              
              <h4>Installation</h4>
              <ol>
                <li>Install Minecraft Forge or Fabric for your Minecraft version</li>
                <li>Download the Create mod from <a href="https://www.curseforge.com/minecraft/mc-mods/create" target="_blank" rel="noopener noreferrer">CurseForge</a></li>
                <li>Place the downloaded .jar file in your Minecraft mods folder</li>
                <li>Launch Minecraft and verify the mod is loaded correctly</li>
              </ol>
              
              <h4>Basic Concepts</h4>
              <p>
                The Create mod revolves around several key concepts:
              </p>
              <ul>
                <li><strong>Rotational Power</strong>: Generated by water wheels, windmills, or steam engines</li>
                <li><strong>Kinetic Mechanisms</strong>: Machines that use rotational power to perform tasks</li>
                <li><strong>Contraptions</strong>: Assemblies of blocks that can move together</li>
                <li><strong>Schematics</strong>: Saved designs that can be shared and rebuilt</li>
              </ul>
              
              <h3>Using Schematics</h3>
              
              <h4>Loading a Schematic</h4>
              <ol>
                <li>Download a schematic file (.nbt) from CreateMod.com</li>
                <li>Place the file in your <code>minecraft/schematics</code> folder</li>
                <li>In-game, craft a Schematic Table and a Schematic and Quill</li>
                <li>Right-click the Schematic Table with the Schematic and Quill</li>
                <li>Select "Load" and choose your downloaded schematic</li>
              </ol>
              
              <h4>Building from a Schematic</h4>
              <ol>
                <li>Craft a Schematicannon</li>
                <li>Place your loaded schematic in the Schematicannon</li>
                <li>Supply the required blocks in the Schematicannon's inventory</li>
                <li>Provide gunpowder for fuel</li>
                <li>Activate the Schematicannon to begin building</li>
              </ol>
              
              <h3>Creating and Sharing Schematics</h3>
              
              <h4>Creating a Schematic</h4>
              <ol>
                <li>Build your creation in-game</li>
                <li>Craft a Schematic and Quill</li>
                <li>Right-click on a block to set the first corner of your selection</li>
                <li>Right-click on another block to set the opposite corner</li>
                <li>Name your schematic and save it</li>
              </ol>
              
              <h4>Sharing on CreateMod.com</h4>
              <ol>
                <li><Link href="/login">Create an account</Link> or log in to CreateMod.com</li>
                <li>Go to the <Link href="/upload">Upload page</Link></li>
                <li>Fill in the details about your schematic</li>
                <li>Upload your .nbt file and screenshots</li>
                <li>Submit your schematic for others to enjoy</li>
              </ol>
              
              <h3>Advanced Techniques</h3>
              
              <h4>Rotational Power Management</h4>
              <p>
                Efficiently managing rotational power is crucial for complex builds:
              </p>
              <ul>
                <li>Use gearboxes to change the direction of rotation</li>
                <li>Use gearshifts to control when power is transmitted</li>
                <li>Use clutches to disconnect parts of your system</li>
                <li>Use chain drives to transfer power over distances</li>
              </ul>
              
              <h4>Automation Tips</h4>
              <p>
                Create mod excels at automation:
              </p>
              <ul>
                <li>Use mechanical arms for item sorting and transfer</li>
                <li>Use deployers for automatic crafting and block placement</li>
                <li>Use mechanical saws and drills for resource gathering</li>
                <li>Use funnels and chutes for item management</li>
              </ul>
              
              <h3>Troubleshooting</h3>
              
              <h4>Common Issues</h4>
              <ul>
                <li><strong>Insufficient Power</strong>: Add more power sources or reduce the load</li>
                <li><strong>Stress Overload</strong>: Your system is trying to do too much with too little power</li>
                <li><strong>Incorrect Rotation</strong>: Check the direction of your gears and shafts</li>
                <li><strong>Schematic Not Loading</strong>: Ensure the file is in the correct folder and format</li>
              </ul>
              
              <h3>Additional Resources</h3>
              <ul>
                <li><a href="https://github.com/Creators-of-Create/Create/wiki" target="_blank" rel="noopener noreferrer">Official Create Wiki</a></li>
                <li><a href="https://www.youtube.com/c/Simibubi" target="_blank" rel="noopener noreferrer">Create Mod YouTube Channel</a></li>
                <li><Link href="/search">Browse Schematics</Link> for inspiration</li>
                <li><Link href="/contact">Contact Us</Link> for help with the website</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}

/**
 * Server-side data fetching
 * 
 * @param {Object} context - Next.js context
 * @returns {Object} - Props for the page component
 */
export async function getServerSideProps(context) {
  try {
    // Get categories for sidebar
    const categoriesData = await getCategories();
    const categories = categoriesData.items || [];
    
    return {
      props: {
        categories
      }
    };
  } catch (error) {
    console.error('Error fetching data for guide page:', error);
    
    // Return empty data on error
    return {
      props: {
        categories: []
      }
    };
  }
}