ALTER TABLE external_auths ADD COLUMN IF NOT EXISTS access_token_encrypted TEXT NOT NULL DEFAULT '';
ALTER TABLE external_auths ADD COLUMN IF NOT EXISTS refresh_token_encrypted TEXT NOT NULL DEFAULT '';
ALTER TABLE external_auths ADD COLUMN IF NOT EXISTS token_expiry TIMESTAMPTZ;
ALTER TABLE external_auths ADD COLUMN IF NOT EXISTS username TEXT NOT NULL DEFAULT '';
ALTER TABLE external_auths ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';
ALTER TABLE external_auths ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}';
