ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS schematic_file TEXT NOT NULL DEFAULT '';
ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS changelog TEXT NOT NULL DEFAULT '';
ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS block_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS dim_x INTEGER NOT NULL DEFAULT 0;
ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS dim_y INTEGER NOT NULL DEFAULT 0;
ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS dim_z INTEGER NOT NULL DEFAULT 0;
ALTER TABLE schematic_versions ADD COLUMN IF NOT EXISTS materials JSONB NOT NULL DEFAULT '{}';
