// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                               = new(Query)
	QeyKryWEactionschedulerAction   *qeyKryWEactionschedulerAction
	QeyKryWEactionschedulerClaim    *qeyKryWEactionschedulerClaim
	QeyKryWEactionschedulerGroup    *qeyKryWEactionschedulerGroup
	QeyKryWEactionschedulerLog      *qeyKryWEactionschedulerLog
	QeyKryWEcomment                 *qeyKryWEcomment
	QeyKryWEcommentmetum            *qeyKryWEcommentmetum
	QeyKryWEfeaSubmission           *qeyKryWEfeaSubmission
	QeyKryWEisInvertedIndex         *qeyKryWEisInvertedIndex
	QeyKryWEjetpackWafBlocklog      *qeyKryWEjetpackWafBlocklog
	QeyKryWElikeDislikeBtnDetail    *qeyKryWElikeDislikeBtnDetail
	QeyKryWElink                    *qeyKryWElink
	QeyKryWEmrRatingItem            *qeyKryWEmrRatingItem
	QeyKryWEmrRatingItemEntry       *qeyKryWEmrRatingItemEntry
	QeyKryWEmrRatingItemEntryValue  *qeyKryWEmrRatingItemEntryValue
	QeyKryWEmrRatingSubject         *qeyKryWEmrRatingSubject
	QeyKryWEnggAlbum                *qeyKryWEnggAlbum
	QeyKryWEnggGallery              *qeyKryWEnggGallery
	QeyKryWEnggPicture              *qeyKryWEnggPicture
	QeyKryWEoption                  *qeyKryWEoption
	QeyKryWEpost                    *qeyKryWEpost
	QeyKryWEpostView                *qeyKryWEpostView
	QeyKryWEpostmetum               *qeyKryWEpostmetum
	QeyKryWEsmushDirImage           *qeyKryWEsmushDirImage
	QeyKryWEsnippet                 *qeyKryWEsnippet
	QeyKryWEterm                    *qeyKryWEterm
	QeyKryWEtermRelationship        *qeyKryWEtermRelationship
	QeyKryWEtermTaxonomy            *qeyKryWEtermTaxonomy
	QeyKryWEtermmetum               *qeyKryWEtermmetum
	QeyKryWEulike                   *qeyKryWEulike
	QeyKryWEulikeActivity           *qeyKryWEulikeActivity
	QeyKryWEulikeComment            *qeyKryWEulikeComment
	QeyKryWEulikeForum              *qeyKryWEulikeForum
	QeyKryWEulikeMetum              *qeyKryWEulikeMetum
	QeyKryWEuser                    *qeyKryWEuser
	QeyKryWEuserRegistrationSession *qeyKryWEuserRegistrationSession
	QeyKryWEusermetum               *qeyKryWEusermetum
	QeyKryWEwcCommentsSubscription  *qeyKryWEwcCommentsSubscription
	QeyKryWEwcFeedbackForm          *qeyKryWEwcFeedbackForm
	QeyKryWEwcFollowUser            *qeyKryWEwcFollowUser
	QeyKryWEwcPhrase                *qeyKryWEwcPhrase
	QeyKryWEwcUsersRated            *qeyKryWEwcUsersRated
	QeyKryWEwcUsersVoted            *qeyKryWEwcUsersVoted
	QeyKryWEwfblockediplog          *qeyKryWEwfblockediplog
	QeyKryWEwfblocks7               *qeyKryWEwfblocks7
	QeyKryWEwfconfig                *qeyKryWEwfconfig
	QeyKryWEwfcrawler               *qeyKryWEwfcrawler
	QeyKryWEwffilechange            *qeyKryWEwffilechange
	QeyKryWEwffilemod               *qeyKryWEwffilemod
	QeyKryWEwfhit                   *qeyKryWEwfhit
	QeyKryWEwfhoover                *qeyKryWEwfhoover
	QeyKryWEwfissue                 *qeyKryWEwfissue
	QeyKryWEwfknownfilelist         *qeyKryWEwfknownfilelist
	QeyKryWEwflivetraffichuman      *qeyKryWEwflivetraffichuman
	QeyKryWEwfloc                   *qeyKryWEwfloc
	QeyKryWEwflogin                 *qeyKryWEwflogin
	QeyKryWEwfls2faSecret           *qeyKryWEwfls2faSecret
	QeyKryWEwflsRoleCount           *qeyKryWEwflsRoleCount
	QeyKryWEwflsSetting             *qeyKryWEwflsSetting
	QeyKryWEwfnotification          *qeyKryWEwfnotification
	QeyKryWEwfpendingissue          *qeyKryWEwfpendingissue
	QeyKryWEwfreversecache          *qeyKryWEwfreversecache
	QeyKryWEwfsecurityevent         *qeyKryWEwfsecurityevent
	QeyKryWEwfsnipcache             *qeyKryWEwfsnipcache
	QeyKryWEwfstatus                *qeyKryWEwfstatus
	QeyKryWEwftrafficrate           *qeyKryWEwftrafficrate
	QeyKryWEwfwaffailure            *qeyKryWEwfwaffailure
	QeyKryWEwpacLikeSystem          *qeyKryWEwpacLikeSystem
	QeyKryWEwpacReactionsSystem     *qeyKryWEwpacReactionsSystem
	QeyKryWEwpfmBackup              *qeyKryWEwpfmBackup
	QeyKryWEwpmailsmtpDebugEvent    *qeyKryWEwpmailsmtpDebugEvent
	QeyKryWEwpmailsmtpTasksMetum    *qeyKryWEwpmailsmtpTasksMetum
	QeyKryWEyoastIndexable          *qeyKryWEyoastIndexable
	QeyKryWEyoastIndexableHierarchy *qeyKryWEyoastIndexableHierarchy
	QeyKryWEyoastMigration          *qeyKryWEyoastMigration
	QeyKryWEyoastPrimaryTerm        *qeyKryWEyoastPrimaryTerm
	QeyKryWEyoastSeoLink            *qeyKryWEyoastSeoLink
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	QeyKryWEactionschedulerAction = &Q.QeyKryWEactionschedulerAction
	QeyKryWEactionschedulerClaim = &Q.QeyKryWEactionschedulerClaim
	QeyKryWEactionschedulerGroup = &Q.QeyKryWEactionschedulerGroup
	QeyKryWEactionschedulerLog = &Q.QeyKryWEactionschedulerLog
	QeyKryWEcomment = &Q.QeyKryWEcomment
	QeyKryWEcommentmetum = &Q.QeyKryWEcommentmetum
	QeyKryWEfeaSubmission = &Q.QeyKryWEfeaSubmission
	QeyKryWEisInvertedIndex = &Q.QeyKryWEisInvertedIndex
	QeyKryWEjetpackWafBlocklog = &Q.QeyKryWEjetpackWafBlocklog
	QeyKryWElikeDislikeBtnDetail = &Q.QeyKryWElikeDislikeBtnDetail
	QeyKryWElink = &Q.QeyKryWElink
	QeyKryWEmrRatingItem = &Q.QeyKryWEmrRatingItem
	QeyKryWEmrRatingItemEntry = &Q.QeyKryWEmrRatingItemEntry
	QeyKryWEmrRatingItemEntryValue = &Q.QeyKryWEmrRatingItemEntryValue
	QeyKryWEmrRatingSubject = &Q.QeyKryWEmrRatingSubject
	QeyKryWEnggAlbum = &Q.QeyKryWEnggAlbum
	QeyKryWEnggGallery = &Q.QeyKryWEnggGallery
	QeyKryWEnggPicture = &Q.QeyKryWEnggPicture
	QeyKryWEoption = &Q.QeyKryWEoption
	QeyKryWEpost = &Q.QeyKryWEpost
	QeyKryWEpostView = &Q.QeyKryWEpostView
	QeyKryWEpostmetum = &Q.QeyKryWEpostmetum
	QeyKryWEsmushDirImage = &Q.QeyKryWEsmushDirImage
	QeyKryWEsnippet = &Q.QeyKryWEsnippet
	QeyKryWEterm = &Q.QeyKryWEterm
	QeyKryWEtermRelationship = &Q.QeyKryWEtermRelationship
	QeyKryWEtermTaxonomy = &Q.QeyKryWEtermTaxonomy
	QeyKryWEtermmetum = &Q.QeyKryWEtermmetum
	QeyKryWEulike = &Q.QeyKryWEulike
	QeyKryWEulikeActivity = &Q.QeyKryWEulikeActivity
	QeyKryWEulikeComment = &Q.QeyKryWEulikeComment
	QeyKryWEulikeForum = &Q.QeyKryWEulikeForum
	QeyKryWEulikeMetum = &Q.QeyKryWEulikeMetum
	QeyKryWEuser = &Q.QeyKryWEuser
	QeyKryWEuserRegistrationSession = &Q.QeyKryWEuserRegistrationSession
	QeyKryWEusermetum = &Q.QeyKryWEusermetum
	QeyKryWEwcCommentsSubscription = &Q.QeyKryWEwcCommentsSubscription
	QeyKryWEwcFeedbackForm = &Q.QeyKryWEwcFeedbackForm
	QeyKryWEwcFollowUser = &Q.QeyKryWEwcFollowUser
	QeyKryWEwcPhrase = &Q.QeyKryWEwcPhrase
	QeyKryWEwcUsersRated = &Q.QeyKryWEwcUsersRated
	QeyKryWEwcUsersVoted = &Q.QeyKryWEwcUsersVoted
	QeyKryWEwfblockediplog = &Q.QeyKryWEwfblockediplog
	QeyKryWEwfblocks7 = &Q.QeyKryWEwfblocks7
	QeyKryWEwfconfig = &Q.QeyKryWEwfconfig
	QeyKryWEwfcrawler = &Q.QeyKryWEwfcrawler
	QeyKryWEwffilechange = &Q.QeyKryWEwffilechange
	QeyKryWEwffilemod = &Q.QeyKryWEwffilemod
	QeyKryWEwfhit = &Q.QeyKryWEwfhit
	QeyKryWEwfhoover = &Q.QeyKryWEwfhoover
	QeyKryWEwfissue = &Q.QeyKryWEwfissue
	QeyKryWEwfknownfilelist = &Q.QeyKryWEwfknownfilelist
	QeyKryWEwflivetraffichuman = &Q.QeyKryWEwflivetraffichuman
	QeyKryWEwfloc = &Q.QeyKryWEwfloc
	QeyKryWEwflogin = &Q.QeyKryWEwflogin
	QeyKryWEwfls2faSecret = &Q.QeyKryWEwfls2faSecret
	QeyKryWEwflsRoleCount = &Q.QeyKryWEwflsRoleCount
	QeyKryWEwflsSetting = &Q.QeyKryWEwflsSetting
	QeyKryWEwfnotification = &Q.QeyKryWEwfnotification
	QeyKryWEwfpendingissue = &Q.QeyKryWEwfpendingissue
	QeyKryWEwfreversecache = &Q.QeyKryWEwfreversecache
	QeyKryWEwfsecurityevent = &Q.QeyKryWEwfsecurityevent
	QeyKryWEwfsnipcache = &Q.QeyKryWEwfsnipcache
	QeyKryWEwfstatus = &Q.QeyKryWEwfstatus
	QeyKryWEwftrafficrate = &Q.QeyKryWEwftrafficrate
	QeyKryWEwfwaffailure = &Q.QeyKryWEwfwaffailure
	QeyKryWEwpacLikeSystem = &Q.QeyKryWEwpacLikeSystem
	QeyKryWEwpacReactionsSystem = &Q.QeyKryWEwpacReactionsSystem
	QeyKryWEwpfmBackup = &Q.QeyKryWEwpfmBackup
	QeyKryWEwpmailsmtpDebugEvent = &Q.QeyKryWEwpmailsmtpDebugEvent
	QeyKryWEwpmailsmtpTasksMetum = &Q.QeyKryWEwpmailsmtpTasksMetum
	QeyKryWEyoastIndexable = &Q.QeyKryWEyoastIndexable
	QeyKryWEyoastIndexableHierarchy = &Q.QeyKryWEyoastIndexableHierarchy
	QeyKryWEyoastMigration = &Q.QeyKryWEyoastMigration
	QeyKryWEyoastPrimaryTerm = &Q.QeyKryWEyoastPrimaryTerm
	QeyKryWEyoastSeoLink = &Q.QeyKryWEyoastSeoLink
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                              db,
		QeyKryWEactionschedulerAction:   newQeyKryWEactionschedulerAction(db, opts...),
		QeyKryWEactionschedulerClaim:    newQeyKryWEactionschedulerClaim(db, opts...),
		QeyKryWEactionschedulerGroup:    newQeyKryWEactionschedulerGroup(db, opts...),
		QeyKryWEactionschedulerLog:      newQeyKryWEactionschedulerLog(db, opts...),
		QeyKryWEcomment:                 newQeyKryWEcomment(db, opts...),
		QeyKryWEcommentmetum:            newQeyKryWEcommentmetum(db, opts...),
		QeyKryWEfeaSubmission:           newQeyKryWEfeaSubmission(db, opts...),
		QeyKryWEisInvertedIndex:         newQeyKryWEisInvertedIndex(db, opts...),
		QeyKryWEjetpackWafBlocklog:      newQeyKryWEjetpackWafBlocklog(db, opts...),
		QeyKryWElikeDislikeBtnDetail:    newQeyKryWElikeDislikeBtnDetail(db, opts...),
		QeyKryWElink:                    newQeyKryWElink(db, opts...),
		QeyKryWEmrRatingItem:            newQeyKryWEmrRatingItem(db, opts...),
		QeyKryWEmrRatingItemEntry:       newQeyKryWEmrRatingItemEntry(db, opts...),
		QeyKryWEmrRatingItemEntryValue:  newQeyKryWEmrRatingItemEntryValue(db, opts...),
		QeyKryWEmrRatingSubject:         newQeyKryWEmrRatingSubject(db, opts...),
		QeyKryWEnggAlbum:                newQeyKryWEnggAlbum(db, opts...),
		QeyKryWEnggGallery:              newQeyKryWEnggGallery(db, opts...),
		QeyKryWEnggPicture:              newQeyKryWEnggPicture(db, opts...),
		QeyKryWEoption:                  newQeyKryWEoption(db, opts...),
		QeyKryWEpost:                    newQeyKryWEpost(db, opts...),
		QeyKryWEpostView:                newQeyKryWEpostView(db, opts...),
		QeyKryWEpostmetum:               newQeyKryWEpostmetum(db, opts...),
		QeyKryWEsmushDirImage:           newQeyKryWEsmushDirImage(db, opts...),
		QeyKryWEsnippet:                 newQeyKryWEsnippet(db, opts...),
		QeyKryWEterm:                    newQeyKryWEterm(db, opts...),
		QeyKryWEtermRelationship:        newQeyKryWEtermRelationship(db, opts...),
		QeyKryWEtermTaxonomy:            newQeyKryWEtermTaxonomy(db, opts...),
		QeyKryWEtermmetum:               newQeyKryWEtermmetum(db, opts...),
		QeyKryWEulike:                   newQeyKryWEulike(db, opts...),
		QeyKryWEulikeActivity:           newQeyKryWEulikeActivity(db, opts...),
		QeyKryWEulikeComment:            newQeyKryWEulikeComment(db, opts...),
		QeyKryWEulikeForum:              newQeyKryWEulikeForum(db, opts...),
		QeyKryWEulikeMetum:              newQeyKryWEulikeMetum(db, opts...),
		QeyKryWEuser:                    newQeyKryWEuser(db, opts...),
		QeyKryWEuserRegistrationSession: newQeyKryWEuserRegistrationSession(db, opts...),
		QeyKryWEusermetum:               newQeyKryWEusermetum(db, opts...),
		QeyKryWEwcCommentsSubscription:  newQeyKryWEwcCommentsSubscription(db, opts...),
		QeyKryWEwcFeedbackForm:          newQeyKryWEwcFeedbackForm(db, opts...),
		QeyKryWEwcFollowUser:            newQeyKryWEwcFollowUser(db, opts...),
		QeyKryWEwcPhrase:                newQeyKryWEwcPhrase(db, opts...),
		QeyKryWEwcUsersRated:            newQeyKryWEwcUsersRated(db, opts...),
		QeyKryWEwcUsersVoted:            newQeyKryWEwcUsersVoted(db, opts...),
		QeyKryWEwfblockediplog:          newQeyKryWEwfblockediplog(db, opts...),
		QeyKryWEwfblocks7:               newQeyKryWEwfblocks7(db, opts...),
		QeyKryWEwfconfig:                newQeyKryWEwfconfig(db, opts...),
		QeyKryWEwfcrawler:               newQeyKryWEwfcrawler(db, opts...),
		QeyKryWEwffilechange:            newQeyKryWEwffilechange(db, opts...),
		QeyKryWEwffilemod:               newQeyKryWEwffilemod(db, opts...),
		QeyKryWEwfhit:                   newQeyKryWEwfhit(db, opts...),
		QeyKryWEwfhoover:                newQeyKryWEwfhoover(db, opts...),
		QeyKryWEwfissue:                 newQeyKryWEwfissue(db, opts...),
		QeyKryWEwfknownfilelist:         newQeyKryWEwfknownfilelist(db, opts...),
		QeyKryWEwflivetraffichuman:      newQeyKryWEwflivetraffichuman(db, opts...),
		QeyKryWEwfloc:                   newQeyKryWEwfloc(db, opts...),
		QeyKryWEwflogin:                 newQeyKryWEwflogin(db, opts...),
		QeyKryWEwfls2faSecret:           newQeyKryWEwfls2faSecret(db, opts...),
		QeyKryWEwflsRoleCount:           newQeyKryWEwflsRoleCount(db, opts...),
		QeyKryWEwflsSetting:             newQeyKryWEwflsSetting(db, opts...),
		QeyKryWEwfnotification:          newQeyKryWEwfnotification(db, opts...),
		QeyKryWEwfpendingissue:          newQeyKryWEwfpendingissue(db, opts...),
		QeyKryWEwfreversecache:          newQeyKryWEwfreversecache(db, opts...),
		QeyKryWEwfsecurityevent:         newQeyKryWEwfsecurityevent(db, opts...),
		QeyKryWEwfsnipcache:             newQeyKryWEwfsnipcache(db, opts...),
		QeyKryWEwfstatus:                newQeyKryWEwfstatus(db, opts...),
		QeyKryWEwftrafficrate:           newQeyKryWEwftrafficrate(db, opts...),
		QeyKryWEwfwaffailure:            newQeyKryWEwfwaffailure(db, opts...),
		QeyKryWEwpacLikeSystem:          newQeyKryWEwpacLikeSystem(db, opts...),
		QeyKryWEwpacReactionsSystem:     newQeyKryWEwpacReactionsSystem(db, opts...),
		QeyKryWEwpfmBackup:              newQeyKryWEwpfmBackup(db, opts...),
		QeyKryWEwpmailsmtpDebugEvent:    newQeyKryWEwpmailsmtpDebugEvent(db, opts...),
		QeyKryWEwpmailsmtpTasksMetum:    newQeyKryWEwpmailsmtpTasksMetum(db, opts...),
		QeyKryWEyoastIndexable:          newQeyKryWEyoastIndexable(db, opts...),
		QeyKryWEyoastIndexableHierarchy: newQeyKryWEyoastIndexableHierarchy(db, opts...),
		QeyKryWEyoastMigration:          newQeyKryWEyoastMigration(db, opts...),
		QeyKryWEyoastPrimaryTerm:        newQeyKryWEyoastPrimaryTerm(db, opts...),
		QeyKryWEyoastSeoLink:            newQeyKryWEyoastSeoLink(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	QeyKryWEactionschedulerAction   qeyKryWEactionschedulerAction
	QeyKryWEactionschedulerClaim    qeyKryWEactionschedulerClaim
	QeyKryWEactionschedulerGroup    qeyKryWEactionschedulerGroup
	QeyKryWEactionschedulerLog      qeyKryWEactionschedulerLog
	QeyKryWEcomment                 qeyKryWEcomment
	QeyKryWEcommentmetum            qeyKryWEcommentmetum
	QeyKryWEfeaSubmission           qeyKryWEfeaSubmission
	QeyKryWEisInvertedIndex         qeyKryWEisInvertedIndex
	QeyKryWEjetpackWafBlocklog      qeyKryWEjetpackWafBlocklog
	QeyKryWElikeDislikeBtnDetail    qeyKryWElikeDislikeBtnDetail
	QeyKryWElink                    qeyKryWElink
	QeyKryWEmrRatingItem            qeyKryWEmrRatingItem
	QeyKryWEmrRatingItemEntry       qeyKryWEmrRatingItemEntry
	QeyKryWEmrRatingItemEntryValue  qeyKryWEmrRatingItemEntryValue
	QeyKryWEmrRatingSubject         qeyKryWEmrRatingSubject
	QeyKryWEnggAlbum                qeyKryWEnggAlbum
	QeyKryWEnggGallery              qeyKryWEnggGallery
	QeyKryWEnggPicture              qeyKryWEnggPicture
	QeyKryWEoption                  qeyKryWEoption
	QeyKryWEpost                    qeyKryWEpost
	QeyKryWEpostView                qeyKryWEpostView
	QeyKryWEpostmetum               qeyKryWEpostmetum
	QeyKryWEsmushDirImage           qeyKryWEsmushDirImage
	QeyKryWEsnippet                 qeyKryWEsnippet
	QeyKryWEterm                    qeyKryWEterm
	QeyKryWEtermRelationship        qeyKryWEtermRelationship
	QeyKryWEtermTaxonomy            qeyKryWEtermTaxonomy
	QeyKryWEtermmetum               qeyKryWEtermmetum
	QeyKryWEulike                   qeyKryWEulike
	QeyKryWEulikeActivity           qeyKryWEulikeActivity
	QeyKryWEulikeComment            qeyKryWEulikeComment
	QeyKryWEulikeForum              qeyKryWEulikeForum
	QeyKryWEulikeMetum              qeyKryWEulikeMetum
	QeyKryWEuser                    qeyKryWEuser
	QeyKryWEuserRegistrationSession qeyKryWEuserRegistrationSession
	QeyKryWEusermetum               qeyKryWEusermetum
	QeyKryWEwcCommentsSubscription  qeyKryWEwcCommentsSubscription
	QeyKryWEwcFeedbackForm          qeyKryWEwcFeedbackForm
	QeyKryWEwcFollowUser            qeyKryWEwcFollowUser
	QeyKryWEwcPhrase                qeyKryWEwcPhrase
	QeyKryWEwcUsersRated            qeyKryWEwcUsersRated
	QeyKryWEwcUsersVoted            qeyKryWEwcUsersVoted
	QeyKryWEwfblockediplog          qeyKryWEwfblockediplog
	QeyKryWEwfblocks7               qeyKryWEwfblocks7
	QeyKryWEwfconfig                qeyKryWEwfconfig
	QeyKryWEwfcrawler               qeyKryWEwfcrawler
	QeyKryWEwffilechange            qeyKryWEwffilechange
	QeyKryWEwffilemod               qeyKryWEwffilemod
	QeyKryWEwfhit                   qeyKryWEwfhit
	QeyKryWEwfhoover                qeyKryWEwfhoover
	QeyKryWEwfissue                 qeyKryWEwfissue
	QeyKryWEwfknownfilelist         qeyKryWEwfknownfilelist
	QeyKryWEwflivetraffichuman      qeyKryWEwflivetraffichuman
	QeyKryWEwfloc                   qeyKryWEwfloc
	QeyKryWEwflogin                 qeyKryWEwflogin
	QeyKryWEwfls2faSecret           qeyKryWEwfls2faSecret
	QeyKryWEwflsRoleCount           qeyKryWEwflsRoleCount
	QeyKryWEwflsSetting             qeyKryWEwflsSetting
	QeyKryWEwfnotification          qeyKryWEwfnotification
	QeyKryWEwfpendingissue          qeyKryWEwfpendingissue
	QeyKryWEwfreversecache          qeyKryWEwfreversecache
	QeyKryWEwfsecurityevent         qeyKryWEwfsecurityevent
	QeyKryWEwfsnipcache             qeyKryWEwfsnipcache
	QeyKryWEwfstatus                qeyKryWEwfstatus
	QeyKryWEwftrafficrate           qeyKryWEwftrafficrate
	QeyKryWEwfwaffailure            qeyKryWEwfwaffailure
	QeyKryWEwpacLikeSystem          qeyKryWEwpacLikeSystem
	QeyKryWEwpacReactionsSystem     qeyKryWEwpacReactionsSystem
	QeyKryWEwpfmBackup              qeyKryWEwpfmBackup
	QeyKryWEwpmailsmtpDebugEvent    qeyKryWEwpmailsmtpDebugEvent
	QeyKryWEwpmailsmtpTasksMetum    qeyKryWEwpmailsmtpTasksMetum
	QeyKryWEyoastIndexable          qeyKryWEyoastIndexable
	QeyKryWEyoastIndexableHierarchy qeyKryWEyoastIndexableHierarchy
	QeyKryWEyoastMigration          qeyKryWEyoastMigration
	QeyKryWEyoastPrimaryTerm        qeyKryWEyoastPrimaryTerm
	QeyKryWEyoastSeoLink            qeyKryWEyoastSeoLink
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                              db,
		QeyKryWEactionschedulerAction:   q.QeyKryWEactionschedulerAction.clone(db),
		QeyKryWEactionschedulerClaim:    q.QeyKryWEactionschedulerClaim.clone(db),
		QeyKryWEactionschedulerGroup:    q.QeyKryWEactionschedulerGroup.clone(db),
		QeyKryWEactionschedulerLog:      q.QeyKryWEactionschedulerLog.clone(db),
		QeyKryWEcomment:                 q.QeyKryWEcomment.clone(db),
		QeyKryWEcommentmetum:            q.QeyKryWEcommentmetum.clone(db),
		QeyKryWEfeaSubmission:           q.QeyKryWEfeaSubmission.clone(db),
		QeyKryWEisInvertedIndex:         q.QeyKryWEisInvertedIndex.clone(db),
		QeyKryWEjetpackWafBlocklog:      q.QeyKryWEjetpackWafBlocklog.clone(db),
		QeyKryWElikeDislikeBtnDetail:    q.QeyKryWElikeDislikeBtnDetail.clone(db),
		QeyKryWElink:                    q.QeyKryWElink.clone(db),
		QeyKryWEmrRatingItem:            q.QeyKryWEmrRatingItem.clone(db),
		QeyKryWEmrRatingItemEntry:       q.QeyKryWEmrRatingItemEntry.clone(db),
		QeyKryWEmrRatingItemEntryValue:  q.QeyKryWEmrRatingItemEntryValue.clone(db),
		QeyKryWEmrRatingSubject:         q.QeyKryWEmrRatingSubject.clone(db),
		QeyKryWEnggAlbum:                q.QeyKryWEnggAlbum.clone(db),
		QeyKryWEnggGallery:              q.QeyKryWEnggGallery.clone(db),
		QeyKryWEnggPicture:              q.QeyKryWEnggPicture.clone(db),
		QeyKryWEoption:                  q.QeyKryWEoption.clone(db),
		QeyKryWEpost:                    q.QeyKryWEpost.clone(db),
		QeyKryWEpostView:                q.QeyKryWEpostView.clone(db),
		QeyKryWEpostmetum:               q.QeyKryWEpostmetum.clone(db),
		QeyKryWEsmushDirImage:           q.QeyKryWEsmushDirImage.clone(db),
		QeyKryWEsnippet:                 q.QeyKryWEsnippet.clone(db),
		QeyKryWEterm:                    q.QeyKryWEterm.clone(db),
		QeyKryWEtermRelationship:        q.QeyKryWEtermRelationship.clone(db),
		QeyKryWEtermTaxonomy:            q.QeyKryWEtermTaxonomy.clone(db),
		QeyKryWEtermmetum:               q.QeyKryWEtermmetum.clone(db),
		QeyKryWEulike:                   q.QeyKryWEulike.clone(db),
		QeyKryWEulikeActivity:           q.QeyKryWEulikeActivity.clone(db),
		QeyKryWEulikeComment:            q.QeyKryWEulikeComment.clone(db),
		QeyKryWEulikeForum:              q.QeyKryWEulikeForum.clone(db),
		QeyKryWEulikeMetum:              q.QeyKryWEulikeMetum.clone(db),
		QeyKryWEuser:                    q.QeyKryWEuser.clone(db),
		QeyKryWEuserRegistrationSession: q.QeyKryWEuserRegistrationSession.clone(db),
		QeyKryWEusermetum:               q.QeyKryWEusermetum.clone(db),
		QeyKryWEwcCommentsSubscription:  q.QeyKryWEwcCommentsSubscription.clone(db),
		QeyKryWEwcFeedbackForm:          q.QeyKryWEwcFeedbackForm.clone(db),
		QeyKryWEwcFollowUser:            q.QeyKryWEwcFollowUser.clone(db),
		QeyKryWEwcPhrase:                q.QeyKryWEwcPhrase.clone(db),
		QeyKryWEwcUsersRated:            q.QeyKryWEwcUsersRated.clone(db),
		QeyKryWEwcUsersVoted:            q.QeyKryWEwcUsersVoted.clone(db),
		QeyKryWEwfblockediplog:          q.QeyKryWEwfblockediplog.clone(db),
		QeyKryWEwfblocks7:               q.QeyKryWEwfblocks7.clone(db),
		QeyKryWEwfconfig:                q.QeyKryWEwfconfig.clone(db),
		QeyKryWEwfcrawler:               q.QeyKryWEwfcrawler.clone(db),
		QeyKryWEwffilechange:            q.QeyKryWEwffilechange.clone(db),
		QeyKryWEwffilemod:               q.QeyKryWEwffilemod.clone(db),
		QeyKryWEwfhit:                   q.QeyKryWEwfhit.clone(db),
		QeyKryWEwfhoover:                q.QeyKryWEwfhoover.clone(db),
		QeyKryWEwfissue:                 q.QeyKryWEwfissue.clone(db),
		QeyKryWEwfknownfilelist:         q.QeyKryWEwfknownfilelist.clone(db),
		QeyKryWEwflivetraffichuman:      q.QeyKryWEwflivetraffichuman.clone(db),
		QeyKryWEwfloc:                   q.QeyKryWEwfloc.clone(db),
		QeyKryWEwflogin:                 q.QeyKryWEwflogin.clone(db),
		QeyKryWEwfls2faSecret:           q.QeyKryWEwfls2faSecret.clone(db),
		QeyKryWEwflsRoleCount:           q.QeyKryWEwflsRoleCount.clone(db),
		QeyKryWEwflsSetting:             q.QeyKryWEwflsSetting.clone(db),
		QeyKryWEwfnotification:          q.QeyKryWEwfnotification.clone(db),
		QeyKryWEwfpendingissue:          q.QeyKryWEwfpendingissue.clone(db),
		QeyKryWEwfreversecache:          q.QeyKryWEwfreversecache.clone(db),
		QeyKryWEwfsecurityevent:         q.QeyKryWEwfsecurityevent.clone(db),
		QeyKryWEwfsnipcache:             q.QeyKryWEwfsnipcache.clone(db),
		QeyKryWEwfstatus:                q.QeyKryWEwfstatus.clone(db),
		QeyKryWEwftrafficrate:           q.QeyKryWEwftrafficrate.clone(db),
		QeyKryWEwfwaffailure:            q.QeyKryWEwfwaffailure.clone(db),
		QeyKryWEwpacLikeSystem:          q.QeyKryWEwpacLikeSystem.clone(db),
		QeyKryWEwpacReactionsSystem:     q.QeyKryWEwpacReactionsSystem.clone(db),
		QeyKryWEwpfmBackup:              q.QeyKryWEwpfmBackup.clone(db),
		QeyKryWEwpmailsmtpDebugEvent:    q.QeyKryWEwpmailsmtpDebugEvent.clone(db),
		QeyKryWEwpmailsmtpTasksMetum:    q.QeyKryWEwpmailsmtpTasksMetum.clone(db),
		QeyKryWEyoastIndexable:          q.QeyKryWEyoastIndexable.clone(db),
		QeyKryWEyoastIndexableHierarchy: q.QeyKryWEyoastIndexableHierarchy.clone(db),
		QeyKryWEyoastMigration:          q.QeyKryWEyoastMigration.clone(db),
		QeyKryWEyoastPrimaryTerm:        q.QeyKryWEyoastPrimaryTerm.clone(db),
		QeyKryWEyoastSeoLink:            q.QeyKryWEyoastSeoLink.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                              db,
		QeyKryWEactionschedulerAction:   q.QeyKryWEactionschedulerAction.replaceDB(db),
		QeyKryWEactionschedulerClaim:    q.QeyKryWEactionschedulerClaim.replaceDB(db),
		QeyKryWEactionschedulerGroup:    q.QeyKryWEactionschedulerGroup.replaceDB(db),
		QeyKryWEactionschedulerLog:      q.QeyKryWEactionschedulerLog.replaceDB(db),
		QeyKryWEcomment:                 q.QeyKryWEcomment.replaceDB(db),
		QeyKryWEcommentmetum:            q.QeyKryWEcommentmetum.replaceDB(db),
		QeyKryWEfeaSubmission:           q.QeyKryWEfeaSubmission.replaceDB(db),
		QeyKryWEisInvertedIndex:         q.QeyKryWEisInvertedIndex.replaceDB(db),
		QeyKryWEjetpackWafBlocklog:      q.QeyKryWEjetpackWafBlocklog.replaceDB(db),
		QeyKryWElikeDislikeBtnDetail:    q.QeyKryWElikeDislikeBtnDetail.replaceDB(db),
		QeyKryWElink:                    q.QeyKryWElink.replaceDB(db),
		QeyKryWEmrRatingItem:            q.QeyKryWEmrRatingItem.replaceDB(db),
		QeyKryWEmrRatingItemEntry:       q.QeyKryWEmrRatingItemEntry.replaceDB(db),
		QeyKryWEmrRatingItemEntryValue:  q.QeyKryWEmrRatingItemEntryValue.replaceDB(db),
		QeyKryWEmrRatingSubject:         q.QeyKryWEmrRatingSubject.replaceDB(db),
		QeyKryWEnggAlbum:                q.QeyKryWEnggAlbum.replaceDB(db),
		QeyKryWEnggGallery:              q.QeyKryWEnggGallery.replaceDB(db),
		QeyKryWEnggPicture:              q.QeyKryWEnggPicture.replaceDB(db),
		QeyKryWEoption:                  q.QeyKryWEoption.replaceDB(db),
		QeyKryWEpost:                    q.QeyKryWEpost.replaceDB(db),
		QeyKryWEpostView:                q.QeyKryWEpostView.replaceDB(db),
		QeyKryWEpostmetum:               q.QeyKryWEpostmetum.replaceDB(db),
		QeyKryWEsmushDirImage:           q.QeyKryWEsmushDirImage.replaceDB(db),
		QeyKryWEsnippet:                 q.QeyKryWEsnippet.replaceDB(db),
		QeyKryWEterm:                    q.QeyKryWEterm.replaceDB(db),
		QeyKryWEtermRelationship:        q.QeyKryWEtermRelationship.replaceDB(db),
		QeyKryWEtermTaxonomy:            q.QeyKryWEtermTaxonomy.replaceDB(db),
		QeyKryWEtermmetum:               q.QeyKryWEtermmetum.replaceDB(db),
		QeyKryWEulike:                   q.QeyKryWEulike.replaceDB(db),
		QeyKryWEulikeActivity:           q.QeyKryWEulikeActivity.replaceDB(db),
		QeyKryWEulikeComment:            q.QeyKryWEulikeComment.replaceDB(db),
		QeyKryWEulikeForum:              q.QeyKryWEulikeForum.replaceDB(db),
		QeyKryWEulikeMetum:              q.QeyKryWEulikeMetum.replaceDB(db),
		QeyKryWEuser:                    q.QeyKryWEuser.replaceDB(db),
		QeyKryWEuserRegistrationSession: q.QeyKryWEuserRegistrationSession.replaceDB(db),
		QeyKryWEusermetum:               q.QeyKryWEusermetum.replaceDB(db),
		QeyKryWEwcCommentsSubscription:  q.QeyKryWEwcCommentsSubscription.replaceDB(db),
		QeyKryWEwcFeedbackForm:          q.QeyKryWEwcFeedbackForm.replaceDB(db),
		QeyKryWEwcFollowUser:            q.QeyKryWEwcFollowUser.replaceDB(db),
		QeyKryWEwcPhrase:                q.QeyKryWEwcPhrase.replaceDB(db),
		QeyKryWEwcUsersRated:            q.QeyKryWEwcUsersRated.replaceDB(db),
		QeyKryWEwcUsersVoted:            q.QeyKryWEwcUsersVoted.replaceDB(db),
		QeyKryWEwfblockediplog:          q.QeyKryWEwfblockediplog.replaceDB(db),
		QeyKryWEwfblocks7:               q.QeyKryWEwfblocks7.replaceDB(db),
		QeyKryWEwfconfig:                q.QeyKryWEwfconfig.replaceDB(db),
		QeyKryWEwfcrawler:               q.QeyKryWEwfcrawler.replaceDB(db),
		QeyKryWEwffilechange:            q.QeyKryWEwffilechange.replaceDB(db),
		QeyKryWEwffilemod:               q.QeyKryWEwffilemod.replaceDB(db),
		QeyKryWEwfhit:                   q.QeyKryWEwfhit.replaceDB(db),
		QeyKryWEwfhoover:                q.QeyKryWEwfhoover.replaceDB(db),
		QeyKryWEwfissue:                 q.QeyKryWEwfissue.replaceDB(db),
		QeyKryWEwfknownfilelist:         q.QeyKryWEwfknownfilelist.replaceDB(db),
		QeyKryWEwflivetraffichuman:      q.QeyKryWEwflivetraffichuman.replaceDB(db),
		QeyKryWEwfloc:                   q.QeyKryWEwfloc.replaceDB(db),
		QeyKryWEwflogin:                 q.QeyKryWEwflogin.replaceDB(db),
		QeyKryWEwfls2faSecret:           q.QeyKryWEwfls2faSecret.replaceDB(db),
		QeyKryWEwflsRoleCount:           q.QeyKryWEwflsRoleCount.replaceDB(db),
		QeyKryWEwflsSetting:             q.QeyKryWEwflsSetting.replaceDB(db),
		QeyKryWEwfnotification:          q.QeyKryWEwfnotification.replaceDB(db),
		QeyKryWEwfpendingissue:          q.QeyKryWEwfpendingissue.replaceDB(db),
		QeyKryWEwfreversecache:          q.QeyKryWEwfreversecache.replaceDB(db),
		QeyKryWEwfsecurityevent:         q.QeyKryWEwfsecurityevent.replaceDB(db),
		QeyKryWEwfsnipcache:             q.QeyKryWEwfsnipcache.replaceDB(db),
		QeyKryWEwfstatus:                q.QeyKryWEwfstatus.replaceDB(db),
		QeyKryWEwftrafficrate:           q.QeyKryWEwftrafficrate.replaceDB(db),
		QeyKryWEwfwaffailure:            q.QeyKryWEwfwaffailure.replaceDB(db),
		QeyKryWEwpacLikeSystem:          q.QeyKryWEwpacLikeSystem.replaceDB(db),
		QeyKryWEwpacReactionsSystem:     q.QeyKryWEwpacReactionsSystem.replaceDB(db),
		QeyKryWEwpfmBackup:              q.QeyKryWEwpfmBackup.replaceDB(db),
		QeyKryWEwpmailsmtpDebugEvent:    q.QeyKryWEwpmailsmtpDebugEvent.replaceDB(db),
		QeyKryWEwpmailsmtpTasksMetum:    q.QeyKryWEwpmailsmtpTasksMetum.replaceDB(db),
		QeyKryWEyoastIndexable:          q.QeyKryWEyoastIndexable.replaceDB(db),
		QeyKryWEyoastIndexableHierarchy: q.QeyKryWEyoastIndexableHierarchy.replaceDB(db),
		QeyKryWEyoastMigration:          q.QeyKryWEyoastMigration.replaceDB(db),
		QeyKryWEyoastPrimaryTerm:        q.QeyKryWEyoastPrimaryTerm.replaceDB(db),
		QeyKryWEyoastSeoLink:            q.QeyKryWEyoastSeoLink.replaceDB(db),
	}
}

type queryCtx struct {
	QeyKryWEactionschedulerAction   IQeyKryWEactionschedulerActionDo
	QeyKryWEactionschedulerClaim    IQeyKryWEactionschedulerClaimDo
	QeyKryWEactionschedulerGroup    IQeyKryWEactionschedulerGroupDo
	QeyKryWEactionschedulerLog      IQeyKryWEactionschedulerLogDo
	QeyKryWEcomment                 IQeyKryWEcommentDo
	QeyKryWEcommentmetum            IQeyKryWEcommentmetumDo
	QeyKryWEfeaSubmission           IQeyKryWEfeaSubmissionDo
	QeyKryWEisInvertedIndex         IQeyKryWEisInvertedIndexDo
	QeyKryWEjetpackWafBlocklog      IQeyKryWEjetpackWafBlocklogDo
	QeyKryWElikeDislikeBtnDetail    IQeyKryWElikeDislikeBtnDetailDo
	QeyKryWElink                    IQeyKryWElinkDo
	QeyKryWEmrRatingItem            IQeyKryWEmrRatingItemDo
	QeyKryWEmrRatingItemEntry       IQeyKryWEmrRatingItemEntryDo
	QeyKryWEmrRatingItemEntryValue  IQeyKryWEmrRatingItemEntryValueDo
	QeyKryWEmrRatingSubject         IQeyKryWEmrRatingSubjectDo
	QeyKryWEnggAlbum                IQeyKryWEnggAlbumDo
	QeyKryWEnggGallery              IQeyKryWEnggGalleryDo
	QeyKryWEnggPicture              IQeyKryWEnggPictureDo
	QeyKryWEoption                  IQeyKryWEoptionDo
	QeyKryWEpost                    IQeyKryWEpostDo
	QeyKryWEpostView                IQeyKryWEpostViewDo
	QeyKryWEpostmetum               IQeyKryWEpostmetumDo
	QeyKryWEsmushDirImage           IQeyKryWEsmushDirImageDo
	QeyKryWEsnippet                 IQeyKryWEsnippetDo
	QeyKryWEterm                    IQeyKryWEtermDo
	QeyKryWEtermRelationship        IQeyKryWEtermRelationshipDo
	QeyKryWEtermTaxonomy            IQeyKryWEtermTaxonomyDo
	QeyKryWEtermmetum               IQeyKryWEtermmetumDo
	QeyKryWEulike                   IQeyKryWEulikeDo
	QeyKryWEulikeActivity           IQeyKryWEulikeActivityDo
	QeyKryWEulikeComment            IQeyKryWEulikeCommentDo
	QeyKryWEulikeForum              IQeyKryWEulikeForumDo
	QeyKryWEulikeMetum              IQeyKryWEulikeMetumDo
	QeyKryWEuser                    IQeyKryWEuserDo
	QeyKryWEuserRegistrationSession IQeyKryWEuserRegistrationSessionDo
	QeyKryWEusermetum               IQeyKryWEusermetumDo
	QeyKryWEwcCommentsSubscription  IQeyKryWEwcCommentsSubscriptionDo
	QeyKryWEwcFeedbackForm          IQeyKryWEwcFeedbackFormDo
	QeyKryWEwcFollowUser            IQeyKryWEwcFollowUserDo
	QeyKryWEwcPhrase                IQeyKryWEwcPhraseDo
	QeyKryWEwcUsersRated            IQeyKryWEwcUsersRatedDo
	QeyKryWEwcUsersVoted            IQeyKryWEwcUsersVotedDo
	QeyKryWEwfblockediplog          IQeyKryWEwfblockediplogDo
	QeyKryWEwfblocks7               IQeyKryWEwfblocks7Do
	QeyKryWEwfconfig                IQeyKryWEwfconfigDo
	QeyKryWEwfcrawler               IQeyKryWEwfcrawlerDo
	QeyKryWEwffilechange            IQeyKryWEwffilechangeDo
	QeyKryWEwffilemod               IQeyKryWEwffilemodDo
	QeyKryWEwfhit                   IQeyKryWEwfhitDo
	QeyKryWEwfhoover                IQeyKryWEwfhooverDo
	QeyKryWEwfissue                 IQeyKryWEwfissueDo
	QeyKryWEwfknownfilelist         IQeyKryWEwfknownfilelistDo
	QeyKryWEwflivetraffichuman      IQeyKryWEwflivetraffichumanDo
	QeyKryWEwfloc                   IQeyKryWEwflocDo
	QeyKryWEwflogin                 IQeyKryWEwfloginDo
	QeyKryWEwfls2faSecret           IQeyKryWEwfls2faSecretDo
	QeyKryWEwflsRoleCount           IQeyKryWEwflsRoleCountDo
	QeyKryWEwflsSetting             IQeyKryWEwflsSettingDo
	QeyKryWEwfnotification          IQeyKryWEwfnotificationDo
	QeyKryWEwfpendingissue          IQeyKryWEwfpendingissueDo
	QeyKryWEwfreversecache          IQeyKryWEwfreversecacheDo
	QeyKryWEwfsecurityevent         IQeyKryWEwfsecurityeventDo
	QeyKryWEwfsnipcache             IQeyKryWEwfsnipcacheDo
	QeyKryWEwfstatus                IQeyKryWEwfstatusDo
	QeyKryWEwftrafficrate           IQeyKryWEwftrafficrateDo
	QeyKryWEwfwaffailure            IQeyKryWEwfwaffailureDo
	QeyKryWEwpacLikeSystem          IQeyKryWEwpacLikeSystemDo
	QeyKryWEwpacReactionsSystem     IQeyKryWEwpacReactionsSystemDo
	QeyKryWEwpfmBackup              IQeyKryWEwpfmBackupDo
	QeyKryWEwpmailsmtpDebugEvent    IQeyKryWEwpmailsmtpDebugEventDo
	QeyKryWEwpmailsmtpTasksMetum    IQeyKryWEwpmailsmtpTasksMetumDo
	QeyKryWEyoastIndexable          IQeyKryWEyoastIndexableDo
	QeyKryWEyoastIndexableHierarchy IQeyKryWEyoastIndexableHierarchyDo
	QeyKryWEyoastMigration          IQeyKryWEyoastMigrationDo
	QeyKryWEyoastPrimaryTerm        IQeyKryWEyoastPrimaryTermDo
	QeyKryWEyoastSeoLink            IQeyKryWEyoastSeoLinkDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		QeyKryWEactionschedulerAction:   q.QeyKryWEactionschedulerAction.WithContext(ctx),
		QeyKryWEactionschedulerClaim:    q.QeyKryWEactionschedulerClaim.WithContext(ctx),
		QeyKryWEactionschedulerGroup:    q.QeyKryWEactionschedulerGroup.WithContext(ctx),
		QeyKryWEactionschedulerLog:      q.QeyKryWEactionschedulerLog.WithContext(ctx),
		QeyKryWEcomment:                 q.QeyKryWEcomment.WithContext(ctx),
		QeyKryWEcommentmetum:            q.QeyKryWEcommentmetum.WithContext(ctx),
		QeyKryWEfeaSubmission:           q.QeyKryWEfeaSubmission.WithContext(ctx),
		QeyKryWEisInvertedIndex:         q.QeyKryWEisInvertedIndex.WithContext(ctx),
		QeyKryWEjetpackWafBlocklog:      q.QeyKryWEjetpackWafBlocklog.WithContext(ctx),
		QeyKryWElikeDislikeBtnDetail:    q.QeyKryWElikeDislikeBtnDetail.WithContext(ctx),
		QeyKryWElink:                    q.QeyKryWElink.WithContext(ctx),
		QeyKryWEmrRatingItem:            q.QeyKryWEmrRatingItem.WithContext(ctx),
		QeyKryWEmrRatingItemEntry:       q.QeyKryWEmrRatingItemEntry.WithContext(ctx),
		QeyKryWEmrRatingItemEntryValue:  q.QeyKryWEmrRatingItemEntryValue.WithContext(ctx),
		QeyKryWEmrRatingSubject:         q.QeyKryWEmrRatingSubject.WithContext(ctx),
		QeyKryWEnggAlbum:                q.QeyKryWEnggAlbum.WithContext(ctx),
		QeyKryWEnggGallery:              q.QeyKryWEnggGallery.WithContext(ctx),
		QeyKryWEnggPicture:              q.QeyKryWEnggPicture.WithContext(ctx),
		QeyKryWEoption:                  q.QeyKryWEoption.WithContext(ctx),
		QeyKryWEpost:                    q.QeyKryWEpost.WithContext(ctx),
		QeyKryWEpostView:                q.QeyKryWEpostView.WithContext(ctx),
		QeyKryWEpostmetum:               q.QeyKryWEpostmetum.WithContext(ctx),
		QeyKryWEsmushDirImage:           q.QeyKryWEsmushDirImage.WithContext(ctx),
		QeyKryWEsnippet:                 q.QeyKryWEsnippet.WithContext(ctx),
		QeyKryWEterm:                    q.QeyKryWEterm.WithContext(ctx),
		QeyKryWEtermRelationship:        q.QeyKryWEtermRelationship.WithContext(ctx),
		QeyKryWEtermTaxonomy:            q.QeyKryWEtermTaxonomy.WithContext(ctx),
		QeyKryWEtermmetum:               q.QeyKryWEtermmetum.WithContext(ctx),
		QeyKryWEulike:                   q.QeyKryWEulike.WithContext(ctx),
		QeyKryWEulikeActivity:           q.QeyKryWEulikeActivity.WithContext(ctx),
		QeyKryWEulikeComment:            q.QeyKryWEulikeComment.WithContext(ctx),
		QeyKryWEulikeForum:              q.QeyKryWEulikeForum.WithContext(ctx),
		QeyKryWEulikeMetum:              q.QeyKryWEulikeMetum.WithContext(ctx),
		QeyKryWEuser:                    q.QeyKryWEuser.WithContext(ctx),
		QeyKryWEuserRegistrationSession: q.QeyKryWEuserRegistrationSession.WithContext(ctx),
		QeyKryWEusermetum:               q.QeyKryWEusermetum.WithContext(ctx),
		QeyKryWEwcCommentsSubscription:  q.QeyKryWEwcCommentsSubscription.WithContext(ctx),
		QeyKryWEwcFeedbackForm:          q.QeyKryWEwcFeedbackForm.WithContext(ctx),
		QeyKryWEwcFollowUser:            q.QeyKryWEwcFollowUser.WithContext(ctx),
		QeyKryWEwcPhrase:                q.QeyKryWEwcPhrase.WithContext(ctx),
		QeyKryWEwcUsersRated:            q.QeyKryWEwcUsersRated.WithContext(ctx),
		QeyKryWEwcUsersVoted:            q.QeyKryWEwcUsersVoted.WithContext(ctx),
		QeyKryWEwfblockediplog:          q.QeyKryWEwfblockediplog.WithContext(ctx),
		QeyKryWEwfblocks7:               q.QeyKryWEwfblocks7.WithContext(ctx),
		QeyKryWEwfconfig:                q.QeyKryWEwfconfig.WithContext(ctx),
		QeyKryWEwfcrawler:               q.QeyKryWEwfcrawler.WithContext(ctx),
		QeyKryWEwffilechange:            q.QeyKryWEwffilechange.WithContext(ctx),
		QeyKryWEwffilemod:               q.QeyKryWEwffilemod.WithContext(ctx),
		QeyKryWEwfhit:                   q.QeyKryWEwfhit.WithContext(ctx),
		QeyKryWEwfhoover:                q.QeyKryWEwfhoover.WithContext(ctx),
		QeyKryWEwfissue:                 q.QeyKryWEwfissue.WithContext(ctx),
		QeyKryWEwfknownfilelist:         q.QeyKryWEwfknownfilelist.WithContext(ctx),
		QeyKryWEwflivetraffichuman:      q.QeyKryWEwflivetraffichuman.WithContext(ctx),
		QeyKryWEwfloc:                   q.QeyKryWEwfloc.WithContext(ctx),
		QeyKryWEwflogin:                 q.QeyKryWEwflogin.WithContext(ctx),
		QeyKryWEwfls2faSecret:           q.QeyKryWEwfls2faSecret.WithContext(ctx),
		QeyKryWEwflsRoleCount:           q.QeyKryWEwflsRoleCount.WithContext(ctx),
		QeyKryWEwflsSetting:             q.QeyKryWEwflsSetting.WithContext(ctx),
		QeyKryWEwfnotification:          q.QeyKryWEwfnotification.WithContext(ctx),
		QeyKryWEwfpendingissue:          q.QeyKryWEwfpendingissue.WithContext(ctx),
		QeyKryWEwfreversecache:          q.QeyKryWEwfreversecache.WithContext(ctx),
		QeyKryWEwfsecurityevent:         q.QeyKryWEwfsecurityevent.WithContext(ctx),
		QeyKryWEwfsnipcache:             q.QeyKryWEwfsnipcache.WithContext(ctx),
		QeyKryWEwfstatus:                q.QeyKryWEwfstatus.WithContext(ctx),
		QeyKryWEwftrafficrate:           q.QeyKryWEwftrafficrate.WithContext(ctx),
		QeyKryWEwfwaffailure:            q.QeyKryWEwfwaffailure.WithContext(ctx),
		QeyKryWEwpacLikeSystem:          q.QeyKryWEwpacLikeSystem.WithContext(ctx),
		QeyKryWEwpacReactionsSystem:     q.QeyKryWEwpacReactionsSystem.WithContext(ctx),
		QeyKryWEwpfmBackup:              q.QeyKryWEwpfmBackup.WithContext(ctx),
		QeyKryWEwpmailsmtpDebugEvent:    q.QeyKryWEwpmailsmtpDebugEvent.WithContext(ctx),
		QeyKryWEwpmailsmtpTasksMetum:    q.QeyKryWEwpmailsmtpTasksMetum.WithContext(ctx),
		QeyKryWEyoastIndexable:          q.QeyKryWEyoastIndexable.WithContext(ctx),
		QeyKryWEyoastIndexableHierarchy: q.QeyKryWEyoastIndexableHierarchy.WithContext(ctx),
		QeyKryWEyoastMigration:          q.QeyKryWEyoastMigration.WithContext(ctx),
		QeyKryWEyoastPrimaryTerm:        q.QeyKryWEyoastPrimaryTerm.WithContext(ctx),
		QeyKryWEyoastSeoLink:            q.QeyKryWEyoastSeoLink.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
