name: deploy
on:
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
jobs:
  build-and-deploy:
    name: Build and deploy CreateMod.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1

      - name: Build Go binary
        run: GOOS=linux CGO_ENABLED=0 go build -a -installsuffix cgo -o ./main ./cmd/server/main.go

      - name: Build frontend assets
        run: |
          npm --prefix template install
          npm --prefix template run build

      - name: Clean up unnecessary files
        run: |
          rm -rf .github cmd internal migrations model query server template/node_modules
          rm -f .gitignore Dockerfile go.mod go.sum npm.Dockerfile README.md

      - name: Deploy to production server via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP }}
          remote-user: ${{ secrets.USERNAME }}
          remote-port: ${{ secrets.SFTP_PORT }}
          remote-password: ${{ secrets.PASSWORD }}
          remote-path: /
          sync: full

      - name: Restart production server
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          server-id: ${{ secrets.SERVER_ID }}
          bearer-token: ${{ secrets.BEARER_TOKEN }}
          power-action: restart