name: deploy
on:
  push:
    branches:
      - development
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
jobs:
  build-and-deploy:
    name: Build and deploy CreateMod.com development server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1

      - name: Build Go binary
        run: GOOS=linux CGO_ENABLED=0 go build -a -installsuffix cgo -o ./main ./cmd/server/main.go

      - name: Build frontend assets
        run: |
          npm --prefix template install
          npm --prefix template run build

      - name: Clean up unnecessary files
        run: |
          rm -rf .github cmd internal migrations model query server template/node_modules
          rm -f .gitignore dev.Dockerfile docker-compose.yml Dockerfile go.mod go.sum npm.Dockerfile README.md

      - name: Deploy to development server via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.DEV_SFTP }}
          remote-user: ${{ secrets.DEV_USERNAME }}
          remote-port: ${{ secrets.DEV_SFTP_PORT }}
          remote-password: ${{ secrets.DEV_PASSWORD }}
          remote-path: /
          sync: full